@base=http://127.0.0.1:8000
@space_id=ce946229-9746-46cd-8dd3-b27a2fbfd48a
@subject_id=1944C046-95B3-4CB4-82E2-C789950E29FC
@person_id=99132ae7-25dd-43ba-808e-cdb3b29af285
@space_cbc_id=66da8ea1-5e69-40f2-a720-9937430d582d

# Spaces

### Index spaces

GET {{base}}/spaces

## Sites

### Index space sites

GET {{base}}/spaces/{{space_id}}/sites

## Activities

### List space activities

GET {{base}}/spaces/{{space_id}}/activity

### Show space activity

GET {{base}}/spaces/{{space_id}}/activity/{{space_cbc_id}}

### Show space activitiy result

GET {{base}}/spaces/{{space_id}}/activity/{{space_cbc_id}}/result

## Subjects

### Index subjects in the space

GET {{base}}/spaces/{{space_id}}/subjects

### Show a subject in the space

GET {{base}}/spaces/{{space_id}}/subjects/{{subject_id}}

### Create a subject in the space

POST {{base}}/spaces/{{space_id}}/subjects
Content-Type: application/json

{
  "status": "candidate",
  "status_date": "2025-03-01T12:00:00",
  "performing_biologic_entity": {
    "administrative_gender_code": "M",
    "birth_date": "2000-03-01",
    "death_date": null,
    "death_date_estimated_indicator": false,
    "death_indicator": false,
    "name": {
      "use": "official", "family": "Test", "given": "Dude"
    }
  },
  "assigned_study_site_protocol_version_relationship": [
    "6a8e6e2b-9537-408f-bd92-a5b83ad2e750"
  ]
}

### Lookup a subject

POST {{base}}/spaces/{{space_id}}/subjects/lookup
Content-Type: application/json

{
  "performing_biologic_entity": {
    "name": {
      "use": "official", "family": "Tr", "given": "Do"
    }
  }
}

### Subject observations

#### List subject observations

GET {{base}}/spaces/{{space_id}}/subjects/{{subject_id}}/observation

#### Show subject observation results

GET {{base}}/spaces/{{space_id}}/subjects/{{subject_id}}/observation/8ac78da9-3c23-4770-94e9-ebaee8432b4b/result

## Persons

### Show a person

GET {{base}}/persons/{{person_id}}

### Names

#### Show a person names

GET {{base}}/persons/{{person_id}}/names

#### Create a person name

POST {{base}}/persons/{{person_id}}/names
Content-Type: application/json

{
  "use": "official",
  "family": "Works",
  "given": "Good",
  "prefix": "Jr."
}

#### Update a person name

PATCH {{base}}/persons/{{person_id}}/names/aea59ce0-7630-442d-ba45-8ef490e891c6
Content-Type: application/json

{
  "use": "official",
  "family": "Works",
  "given": "Better",
  "prefix": null
}

#### Delete a person name

DELETE {{base}}/persons/{{person_id}}/names/b0f79211-0160-42c4-9f75-74b38ba156ca

### Postal addresses

#### Show a person postal addresses

GET {{base}}/persons/{{person_id}}/postal_addresses

#### Create a person postal address

POST {{base}}/persons/{{person_id}}/postal_addresses
Content-Type: application/json

{
  "use": "tmp",
  "street": "Pushkina",
  "building": "Kolotushkina",
  "country": "Lukomorje",
  "municipality": "Great tree",
  "state": "",
  "zip": "111111"
}

### Telecommunication addresses

#### Show a person telecommunication addresses

GET {{base}}/persons/{{person_id}}/telecommunication_addresses

#### Create a person telecommunication address

POST {{base}}/persons/{{person_id}}/telecommunication_addresses
Content-Type: application/json

{
  "use": "H",
  "shema": "tel",
  "address": "8(800)5553535"
}
