@base=http://127.0.0.1:8000

# Spaces

### Index spaces

GET {{base}}/spaces

## Sites

### Index sites in the space

GET {{base}}/spaces/ce946229-9746-46cd-8dd3-b27a2fbfd48a/sites

## Subjects

### Index subjects in the space

GET {{base}}/spaces/ce946229-9746-46cd-8dd3-b27a2fbfd48a/subjects

### Show a subject in the space

GET {{base}}/spaces/ce946229-9746-46cd-8dd3-b27a2fbfd48a/subjects/f0519f08-d22f-40ff-8800-cee82c4e925b

### Create a subject in the space

POST {{base}}/spaces/ce946229-9746-46cd-8dd3-b27a2fbfd48a/subjects
Content-Type: application/json

{
  "status": "candidate",
  "status_date": "2025-03-01T12:00:00",
  "performing_biologic_entity": {
    "administrative_gender_code": "M",
    "birth_date": "2000-03-01",
    "death_date": null,
    "death_date_estimated_indicator": false,
    "death_indicator": false,
    "name": {
      "use": "official", "family": "Test", "given": "Dude"
    }
  },
  "assigned_study_site_protocol_version_relationship": [
    "6a8e6e2b-9537-408f-bd92-a5b83ad2e750"
  ]
}

### Lookup a subject

POST {{base}}/spaces/ce946229-9746-46cd-8dd3-b27a2fbfd48a/subjects/lookup
Content-Type: application/json

{
  "performing_biologic_entity": {
    "name": {
      "use": "official", "family": "Test", "given": "Dude"
    }
  }
}

## Persons

### Show a person

GET {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285

### Names

#### Show a person names

GET {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/names

#### Create a person name

POST {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/names
Content-Type: application/json

{
  "use": "official",
  "family": "Works",
  "given": "Good",
  "prefix": "Jr."
}

### Postal addresses

#### Show a person postal addresses

GET {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/postal_addresses

#### Create a person postal address

POST {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/postal_addresses
Content-Type: application/json

{
  "use": "tmp",
  "street": "Pushkina",
  "building": "Kolotushkina",
  "country": "Lukomorje",
  "municipality": "Great tree",
  "state": "",
  "zip": "111111",
}

### Telecommunication addresses

#### Show a person telecommunication addresses

GET {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/telecommunication_addresses

#### Create a person telecommunication address

POST {{base}}/persons/99132ae7-25dd-43ba-808e-cdb3b29af285/telecommunication_addresses
Content-Type: application/json

{
  "use": "h",
  "shema": "tel",
  "address": "8(800)5553535"
}