[project]
name = "uml"
version = "0.1.0"
description = "UML model of BRIDG"

[build-system]
requires = ["uv_build>=0.8.12,<0.9.0"]
build-backend = "uv_build"

[tool.ruff]
extend = "../../pyproject.toml"

[tool.uv.build-backend]
module-root = ""
