/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AdministrativeGender = {
    M: 'M',
    F: 'F',
    U: 'U'
} as const;
export type AdministrativeGender = typeof AdministrativeGender[keyof typeof AdministrativeGender];


export function instanceOfAdministrativeGender(value: any): boolean {
    for (const key in AdministrativeGender) {
        if (Object.prototype.hasOwnProperty.call(AdministrativeGender, key)) {
            if (AdministrativeGender[key as keyof typeof AdministrativeGender] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AdministrativeGenderFromJSON(json: any): AdministrativeGender {
    return AdministrativeGenderFromJSONTyped(json, false);
}

export function AdministrativeGenderFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdministrativeGender {
    return json as AdministrativeGender;
}

export function AdministrativeGenderToJSON(value?: AdministrativeGender | null): any {
    return value as any;
}

export function AdministrativeGenderToJSONTyped(value: any, ignoreDiscriminator: boolean): AdministrativeGender {
    return value as AdministrativeGender;
}

