/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityNameData } from './EntityNameData';
import {
    EntityNameDataFromJSON,
    EntityNameDataFromJSONTyped,
    EntityNameDataToJSON,
    EntityNameDataToJSONTyped,
} from './EntityNameData';
import type { AdministrativeGender } from './AdministrativeGender';
import {
    AdministrativeGenderFromJSON,
    AdministrativeGenderFromJSONTyped,
    AdministrativeGenderToJSON,
    AdministrativeGenderToJSONTyped,
} from './AdministrativeGender';

/**
 * 
 * @export
 * @interface ApiSubjectNewStudySubjectPerson
 */
export interface ApiSubjectNewStudySubjectPerson {
    /**
     * 
     * @type {string}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    type?: string;
    /**
     * 
     * @type {AdministrativeGender}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    administrativeGenderCode?: AdministrativeGender | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    deathDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    deathDateEstimatedIndicator?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    deathIndicator?: boolean | null;
    /**
     * 
     * @type {EntityNameData}
     * @memberof ApiSubjectNewStudySubjectPerson
     */
    name?: EntityNameData | null;
}



/**
 * Check if a given object implements the ApiSubjectNewStudySubjectPerson interface.
 */
export function instanceOfApiSubjectNewStudySubjectPerson(value: object): value is ApiSubjectNewStudySubjectPerson {
    return true;
}

export function ApiSubjectNewStudySubjectPersonFromJSON(json: any): ApiSubjectNewStudySubjectPerson {
    return ApiSubjectNewStudySubjectPersonFromJSONTyped(json, false);
}

export function ApiSubjectNewStudySubjectPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubjectNewStudySubjectPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'administrativeGenderCode': json['administrative_gender_code'] == null ? undefined : AdministrativeGenderFromJSON(json['administrative_gender_code']),
        'birthDate': json['birth_date'] == null ? undefined : (new Date(json['birth_date'])),
        'deathDate': json['death_date'] == null ? undefined : (new Date(json['death_date'])),
        'deathDateEstimatedIndicator': json['death_date_estimated_indicator'] == null ? undefined : json['death_date_estimated_indicator'],
        'deathIndicator': json['death_indicator'] == null ? undefined : json['death_indicator'],
        'name': json['name'] == null ? undefined : EntityNameDataFromJSON(json['name']),
    };
}

export function ApiSubjectNewStudySubjectPersonToJSON(json: any): ApiSubjectNewStudySubjectPerson {
    return ApiSubjectNewStudySubjectPersonToJSONTyped(json, false);
}

export function ApiSubjectNewStudySubjectPersonToJSONTyped(value?: ApiSubjectNewStudySubjectPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'administrative_gender_code': AdministrativeGenderToJSON(value['administrativeGenderCode']),
        'birth_date': value['birthDate'] === null ? null : ((value['birthDate'] as any)?.toISOString().substring(0,10)),
        'death_date': value['deathDate'] === null ? null : ((value['deathDate'] as any)?.toISOString().substring(0,10)),
        'death_date_estimated_indicator': value['deathDateEstimatedIndicator'],
        'death_indicator': value['deathIndicator'],
        'name': EntityNameDataToJSON(value['name']),
    };
}

