/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameWithId
 */
export interface NameWithId {
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    family?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    given?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    middle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    patronymic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    prefix?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NameWithId
     */
    suffix?: string | null;
}

/**
 * Check if a given object implements the NameWithId interface.
 */
export function instanceOfNameWithId(value: object): value is NameWithId {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function NameWithIdFromJSON(json: any): NameWithId {
    return NameWithIdFromJSONTyped(json, false);
}

export function NameWithIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameWithId {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'use': json['use'] == null ? undefined : json['use'],
        'family': json['family'] == null ? undefined : json['family'],
        'given': json['given'] == null ? undefined : json['given'],
        'middle': json['middle'] == null ? undefined : json['middle'],
        'patronymic': json['patronymic'] == null ? undefined : json['patronymic'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function NameWithIdToJSON(json: any): NameWithId {
    return NameWithIdToJSONTyped(json, false);
}

export function NameWithIdToJSONTyped(value?: NameWithId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'use': value['use'],
        'family': value['family'],
        'given': value['given'],
        'middle': value['middle'],
        'patronymic': value['patronymic'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
    };
}

