/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { PersonInput } from './PersonInput';
import {
    PersonInputFromJSON,
    PersonInputFromJSONTyped,
    PersonInputToJSON,
    PersonInputToJSONTyped,
} from './PersonInput';

/**
 * 
 * @export
 * @interface NewStudySubject
 */
export interface NewStudySubject {
    /**
     * 
     * @type {Status}
     * @memberof NewStudySubject
     */
    status?: Status | null;
    /**
     * 
     * @type {Date}
     * @memberof NewStudySubject
     */
    statusDate?: Date | null;
    /**
     * 
     * @type {PersonInput}
     * @memberof NewStudySubject
     */
    performingBiologicEntity?: PersonInput | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewStudySubject
     */
    assignedStudySiteProtocolVersionRelationship: Array<string>;
}



/**
 * Check if a given object implements the NewStudySubject interface.
 */
export function instanceOfNewStudySubject(value: object): value is NewStudySubject {
    if (!('assignedStudySiteProtocolVersionRelationship' in value) || value['assignedStudySiteProtocolVersionRelationship'] === undefined) return false;
    return true;
}

export function NewStudySubjectFromJSON(json: any): NewStudySubject {
    return NewStudySubjectFromJSONTyped(json, false);
}

export function NewStudySubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStudySubject {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : StatusFromJSON(json['status']),
        'statusDate': json['status_date'] == null ? undefined : (new Date(json['status_date'])),
        'performingBiologicEntity': json['performing_biologic_entity'] == null ? undefined : PersonInputFromJSON(json['performing_biologic_entity']),
        'assignedStudySiteProtocolVersionRelationship': json['assigned_study_site_protocol_version_relationship'],
    };
}

export function NewStudySubjectToJSON(json: any): NewStudySubject {
    return NewStudySubjectToJSONTyped(json, false);
}

export function NewStudySubjectToJSONTyped(value?: NewStudySubject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': StatusToJSON(value['status']),
        'status_date': value['statusDate'] === null ? null : ((value['statusDate'] as any)?.toISOString()),
        'performing_biologic_entity': PersonInputToJSON(value['performingBiologicEntity']),
        'assigned_study_site_protocol_version_relationship': value['assignedStudySiteProtocolVersionRelationship'],
    };
}

