/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationName } from './OrganizationName';
import {
    OrganizationNameFromJSON,
    OrganizationNameFromJSONTyped,
    OrganizationNameToJSON,
    OrganizationNameToJSONTyped,
} from './OrganizationName';

/**
 * 
 * @export
 * @interface OrganizationInput
 */
export interface OrganizationInput {
    /**
     * 
     * @type {OrganizationName}
     * @memberof OrganizationInput
     */
    name: OrganizationName;
}

/**
 * Check if a given object implements the OrganizationInput interface.
 */
export function instanceOfOrganizationInput(value: object): value is OrganizationInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function OrganizationInputFromJSON(json: any): OrganizationInput {
    return OrganizationInputFromJSONTyped(json, false);
}

export function OrganizationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': OrganizationNameFromJSON(json['name']),
    };
}

export function OrganizationInputToJSON(json: any): OrganizationInput {
    return OrganizationInputToJSONTyped(json, false);
}

export function OrganizationInputToJSONTyped(value?: OrganizationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': OrganizationNameToJSON(value['name']),
    };
}

