/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationOutput
 */
export interface OrganizationOutput {
    /**
     * 
     * @type {string}
     * @memberof OrganizationOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationOutput
     */
    description: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationOutput
     */
    primaryName: string | null;
}

/**
 * Check if a given object implements the OrganizationOutput interface.
 */
export function instanceOfOrganizationOutput(value: object): value is OrganizationOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('primaryName' in value) || value['primaryName'] === undefined) return false;
    return true;
}

export function OrganizationOutputFromJSON(json: any): OrganizationOutput {
    return OrganizationOutputFromJSONTyped(json, false);
}

export function OrganizationOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'primaryName': json['primary_name'],
    };
}

export function OrganizationOutputToJSON(json: any): OrganizationOutput {
    return OrganizationOutputToJSONTyped(json, false);
}

export function OrganizationOutputToJSONTyped(value?: OrganizationOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
        'primary_name': value['primaryName'],
    };
}

