/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelecommunicationAddress
 */
export interface TelecommunicationAddress {
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddress
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddress
     */
    scheme?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddress
     */
    address?: string | null;
}

/**
 * Check if a given object implements the TelecommunicationAddress interface.
 */
export function instanceOfTelecommunicationAddress(value: object): value is TelecommunicationAddress {
    return true;
}

export function TelecommunicationAddressFromJSON(json: any): TelecommunicationAddress {
    return TelecommunicationAddressFromJSONTyped(json, false);
}

export function TelecommunicationAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelecommunicationAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function TelecommunicationAddressToJSON(json: any): TelecommunicationAddress {
    return TelecommunicationAddressToJSONTyped(json, false);
}

export function TelecommunicationAddressToJSONTyped(value?: TelecommunicationAddress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'scheme': value['scheme'],
        'address': value['address'],
    };
}

