/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpacesSpaceIdSubjectsRouteRouteImport } from './routes/spaces/$spaceId/subjects/route'
import { Route as SpacesSpaceIdSubjectsIndexRouteImport } from './routes/spaces/$spaceId/subjects/index'
import { Route as SpacesSpaceIdSubjectsNewRouteImport } from './routes/spaces/$spaceId/subjects/new'
import { Route as SpacesSpaceIdSubjectsEditRouteImport } from './routes/spaces/$spaceId/subjects/edit'
import { Route as SpacesSpaceIdSubjectsSubjectIdRouteImport } from './routes/spaces/$spaceId/subjects/$subjectId'
import { Route as SpacesSpaceIdSubjectsSubjectIdEditRouteImport } from './routes/spaces/$spaceId/subjects/$subjectId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdSubjectsRouteRoute =
  SpacesSpaceIdSubjectsRouteRouteImport.update({
    id: '/spaces/$spaceId/subjects',
    path: '/spaces/$spaceId/subjects',
    getParentRoute: () => rootRouteImport,
  } as any)
const SpacesSpaceIdSubjectsIndexRoute =
  SpacesSpaceIdSubjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SpacesSpaceIdSubjectsRouteRoute,
  } as any)
const SpacesSpaceIdSubjectsNewRoute =
  SpacesSpaceIdSubjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => SpacesSpaceIdSubjectsRouteRoute,
  } as any)
const SpacesSpaceIdSubjectsEditRoute =
  SpacesSpaceIdSubjectsEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SpacesSpaceIdSubjectsRouteRoute,
  } as any)
const SpacesSpaceIdSubjectsSubjectIdRoute =
  SpacesSpaceIdSubjectsSubjectIdRouteImport.update({
    id: '/$subjectId',
    path: '/$subjectId',
    getParentRoute: () => SpacesSpaceIdSubjectsRouteRoute,
  } as any)
const SpacesSpaceIdSubjectsSubjectIdEditRoute =
  SpacesSpaceIdSubjectsSubjectIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => SpacesSpaceIdSubjectsSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spaces/$spaceId/subjects': typeof SpacesSpaceIdSubjectsRouteRouteWithChildren
  '/spaces/$spaceId/subjects/$subjectId': typeof SpacesSpaceIdSubjectsSubjectIdRouteWithChildren
  '/spaces/$spaceId/subjects/edit': typeof SpacesSpaceIdSubjectsEditRoute
  '/spaces/$spaceId/subjects/new': typeof SpacesSpaceIdSubjectsNewRoute
  '/spaces/$spaceId/subjects/': typeof SpacesSpaceIdSubjectsIndexRoute
  '/spaces/$spaceId/subjects/$subjectId/edit': typeof SpacesSpaceIdSubjectsSubjectIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spaces/$spaceId/subjects/$subjectId': typeof SpacesSpaceIdSubjectsSubjectIdRouteWithChildren
  '/spaces/$spaceId/subjects/edit': typeof SpacesSpaceIdSubjectsEditRoute
  '/spaces/$spaceId/subjects/new': typeof SpacesSpaceIdSubjectsNewRoute
  '/spaces/$spaceId/subjects': typeof SpacesSpaceIdSubjectsIndexRoute
  '/spaces/$spaceId/subjects/$subjectId/edit': typeof SpacesSpaceIdSubjectsSubjectIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spaces/$spaceId/subjects': typeof SpacesSpaceIdSubjectsRouteRouteWithChildren
  '/spaces/$spaceId/subjects/$subjectId': typeof SpacesSpaceIdSubjectsSubjectIdRouteWithChildren
  '/spaces/$spaceId/subjects/edit': typeof SpacesSpaceIdSubjectsEditRoute
  '/spaces/$spaceId/subjects/new': typeof SpacesSpaceIdSubjectsNewRoute
  '/spaces/$spaceId/subjects/': typeof SpacesSpaceIdSubjectsIndexRoute
  '/spaces/$spaceId/subjects/$subjectId/edit': typeof SpacesSpaceIdSubjectsSubjectIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spaces/$spaceId/subjects'
    | '/spaces/$spaceId/subjects/$subjectId'
    | '/spaces/$spaceId/subjects/edit'
    | '/spaces/$spaceId/subjects/new'
    | '/spaces/$spaceId/subjects/'
    | '/spaces/$spaceId/subjects/$subjectId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/spaces/$spaceId/subjects/$subjectId'
    | '/spaces/$spaceId/subjects/edit'
    | '/spaces/$spaceId/subjects/new'
    | '/spaces/$spaceId/subjects'
    | '/spaces/$spaceId/subjects/$subjectId/edit'
  id:
    | '__root__'
    | '/'
    | '/spaces/$spaceId/subjects'
    | '/spaces/$spaceId/subjects/$subjectId'
    | '/spaces/$spaceId/subjects/edit'
    | '/spaces/$spaceId/subjects/new'
    | '/spaces/$spaceId/subjects/'
    | '/spaces/$spaceId/subjects/$subjectId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpacesSpaceIdSubjectsRouteRoute: typeof SpacesSpaceIdSubjectsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/subjects': {
      id: '/spaces/$spaceId/subjects'
      path: '/spaces/$spaceId/subjects'
      fullPath: '/spaces/$spaceId/subjects'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/subjects/': {
      id: '/spaces/$spaceId/subjects/'
      path: '/'
      fullPath: '/spaces/$spaceId/subjects/'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsIndexRouteImport
      parentRoute: typeof SpacesSpaceIdSubjectsRouteRoute
    }
    '/spaces/$spaceId/subjects/new': {
      id: '/spaces/$spaceId/subjects/new'
      path: '/new'
      fullPath: '/spaces/$spaceId/subjects/new'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsNewRouteImport
      parentRoute: typeof SpacesSpaceIdSubjectsRouteRoute
    }
    '/spaces/$spaceId/subjects/edit': {
      id: '/spaces/$spaceId/subjects/edit'
      path: '/edit'
      fullPath: '/spaces/$spaceId/subjects/edit'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsEditRouteImport
      parentRoute: typeof SpacesSpaceIdSubjectsRouteRoute
    }
    '/spaces/$spaceId/subjects/$subjectId': {
      id: '/spaces/$spaceId/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/spaces/$spaceId/subjects/$subjectId'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsSubjectIdRouteImport
      parentRoute: typeof SpacesSpaceIdSubjectsRouteRoute
    }
    '/spaces/$spaceId/subjects/$subjectId/edit': {
      id: '/spaces/$spaceId/subjects/$subjectId/edit'
      path: '/edit'
      fullPath: '/spaces/$spaceId/subjects/$subjectId/edit'
      preLoaderRoute: typeof SpacesSpaceIdSubjectsSubjectIdEditRouteImport
      parentRoute: typeof SpacesSpaceIdSubjectsSubjectIdRoute
    }
  }
}

interface SpacesSpaceIdSubjectsSubjectIdRouteChildren {
  SpacesSpaceIdSubjectsSubjectIdEditRoute: typeof SpacesSpaceIdSubjectsSubjectIdEditRoute
}

const SpacesSpaceIdSubjectsSubjectIdRouteChildren: SpacesSpaceIdSubjectsSubjectIdRouteChildren =
  {
    SpacesSpaceIdSubjectsSubjectIdEditRoute:
      SpacesSpaceIdSubjectsSubjectIdEditRoute,
  }

const SpacesSpaceIdSubjectsSubjectIdRouteWithChildren =
  SpacesSpaceIdSubjectsSubjectIdRoute._addFileChildren(
    SpacesSpaceIdSubjectsSubjectIdRouteChildren,
  )

interface SpacesSpaceIdSubjectsRouteRouteChildren {
  SpacesSpaceIdSubjectsSubjectIdRoute: typeof SpacesSpaceIdSubjectsSubjectIdRouteWithChildren
  SpacesSpaceIdSubjectsEditRoute: typeof SpacesSpaceIdSubjectsEditRoute
  SpacesSpaceIdSubjectsNewRoute: typeof SpacesSpaceIdSubjectsNewRoute
  SpacesSpaceIdSubjectsIndexRoute: typeof SpacesSpaceIdSubjectsIndexRoute
}

const SpacesSpaceIdSubjectsRouteRouteChildren: SpacesSpaceIdSubjectsRouteRouteChildren =
  {
    SpacesSpaceIdSubjectsSubjectIdRoute:
      SpacesSpaceIdSubjectsSubjectIdRouteWithChildren,
    SpacesSpaceIdSubjectsEditRoute: SpacesSpaceIdSubjectsEditRoute,
    SpacesSpaceIdSubjectsNewRoute: SpacesSpaceIdSubjectsNewRoute,
    SpacesSpaceIdSubjectsIndexRoute: SpacesSpaceIdSubjectsIndexRoute,
  }

const SpacesSpaceIdSubjectsRouteRouteWithChildren =
  SpacesSpaceIdSubjectsRouteRoute._addFileChildren(
    SpacesSpaceIdSubjectsRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpacesSpaceIdSubjectsRouteRoute: SpacesSpaceIdSubjectsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
