name: Telegram CI Notification

on:
  workflow_call:
    inputs:
      status_text:
        type: string
        required: true
        description: "Job status (success/failure)"
      status_emoji:
        type: string
        required: true
        description: "Job status emoji (success/failure)"
      stage_name:
        type: string
        required: true
        description: Job stage name
      working_directory:
        type: string
        default: ""
        description: "Project directory (e.g., ./ui)"
      chat_id:
        required: true
      bot_token:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send Telegram Notification
        run: |
            # Construct message
            MESSAGE=$(cat <<EOF
            ${{ inputs.status_emoji }} GitHub Actions CI Report for [${{ inputs.stage_name }}] ${{ inputs.status_emoji }}

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Status: ${{ inputs.status_text }}
            
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Author: ${{ github.actor }}

            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            EOF
            )

            # URL encode the message
            ENCODED_MESSAGE=$(printf '%s' "$MESSAGE" | jq -sRr @uri)

            # Send message via Telegram Bot API
            TELEGRAM_API_URL="https://api.telegram.org/bot${{ inputs.bot_token }}/sendMessage"
            
            RESPONSE=$(curl -s -X POST "$TELEGRAM_API_URL" \
            -d "chat_id=${{ inputs.chat_id }}" \
            -d "text=${ENCODED_MESSAGE}")

            # Check if message was sent successfully
            if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "Telegram notification sent successfully"
            else
            echo "Failed to send Telegram notification"
            echo "$RESPONSE"
            exit 1
            fi