name: Telegram CI Notification

on:
  workflow_call:
    inputs:
      status_text:
        type: string
        required: true
        description: "Job status (success/failure)"
      status_emoji:
        type: string
        required: true
        description: "Job status emoji (success/failure)"
      stage_name:
        type: string
        required: true
        description: Job stage name
      working_directory:
        type: string
        default: ""
        description: "Project directory (e.g., ./ui)"
    secrets:
      chat_id:
        required: true
      bot_token:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send Telegram Notification
        env:
          WORKING_DIR: ${{ inputs.working_directory }}
          TELEGRAM_CHAT_ID: ${{ secrets.chat_id }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.bot_token }}
          STATUS_TEXT: ${{ inputs.status_text }}
          STATUS_EMOJI: ${{ inputs.status_emoji }}
          STAGE_NAME: ${{ inputs.stage_name }}
        run: |
            # Construct message
            MESSAGE=$(cat <<EOF
            ${STATUS_EMOJI} GitHub Actions CI Report for [${STAGE_NAME}] ${STATUS_EMOJI}

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Status: ${STATUS_TEXT}
            
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Author: ${{ github.actor }}

            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            EOF
            )

            # URL encode the message
            ENCODED_MESSAGE=$(printf '%s' "$MESSAGE" | jq -sRr @uri)

            # Send message via Telegram Bot API
            TELEGRAM_API_URL="https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
            
            RESPONSE=$(curl -s -X POST "$TELEGRAM_API_URL" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "text=${ENCODED_MESSAGE}")

            # Check if message was sent successfully
            if echo "$RESPONSE" | grep -q '"ok":true'; then
            echo "Telegram notification sent successfully"
            else
            echo "Failed to send Telegram notification"
            echo "$RESPONSE"
            exit 1
            fi