/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConceptDescriptor,
  HTTPValidationError,
} from '../models/index';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ExpandCodeSystemRequest {
    codeSystem: string;
}

/**
 * 
 */
export class CodeSystemApi extends runtime.BaseAPI {

    /**
     * Expand
     */
    async expandCodeSystemRaw(requestParameters: ExpandCodeSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ConceptDescriptor>>> {
        if (requestParameters['codeSystem'] == null) {
            throw new runtime.RequiredError(
                'codeSystem',
                'Required parameter "codeSystem" was null or undefined when calling expandCodeSystem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/code_system/{code_system}/$expand`;
        urlPath = urlPath.replace(`{${"code_system"}}`, encodeURIComponent(String(requestParameters['codeSystem'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConceptDescriptorFromJSON));
    }

    /**
     * Expand
     */
    async expandCodeSystem(requestParameters: ExpandCodeSystemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConceptDescriptor>> {
        const response = await this.expandCodeSystemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
