/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Epoch,
  HTTPValidationError,
  StudyProtocolVersion,
  StudySiteProtocolVersionRelationship,
} from '../models/index';
import {
    EpochFromJSON,
    EpochToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    StudyProtocolVersionFromJSON,
    StudyProtocolVersionToJSON,
    StudySiteProtocolVersionRelationshipFromJSON,
    StudySiteProtocolVersionRelationshipToJSON,
} from '../models/index';

export interface IndexEpochSpacesSpaceIdEpochGetRequest {
    spaceId: string;
}

export interface IndexSiteSpacesSpaceIdSiteGetRequest {
    spaceId: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Index Epoch
     */
    async indexEpochSpacesSpaceIdEpochGetRaw(requestParameters: IndexEpochSpacesSpaceIdEpochGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Epoch>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexEpochSpacesSpaceIdEpochGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces/{space_id}/epoch`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EpochFromJSON));
    }

    /**
     * Index Epoch
     */
    async indexEpochSpacesSpaceIdEpochGet(requestParameters: IndexEpochSpacesSpaceIdEpochGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Epoch>> {
        const response = await this.indexEpochSpacesSpaceIdEpochGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Index
     */
    async indexGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.indexGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Index Site
     */
    async indexSiteSpacesSpaceIdSiteGetRaw(requestParameters: IndexSiteSpacesSpaceIdSiteGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StudySiteProtocolVersionRelationship>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSiteSpacesSpaceIdSiteGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces/{space_id}/site`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StudySiteProtocolVersionRelationshipFromJSON));
    }

    /**
     * Index Site
     */
    async indexSiteSpacesSpaceIdSiteGet(requestParameters: IndexSiteSpacesSpaceIdSiteGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StudySiteProtocolVersionRelationship>> {
        const response = await this.indexSiteSpacesSpaceIdSiteGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexSpacesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StudyProtocolVersion>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StudyProtocolVersionFromJSON));
    }

    /**
     * Index
     */
    async indexSpacesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StudyProtocolVersion>> {
        const response = await this.indexSpacesGetRaw(initOverrides);
        return await response.value();
    }

}
