/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StudyProtocolVersion,
} from '../models/index';
import {
    StudyProtocolVersionFromJSON,
    StudyProtocolVersionToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Index
     */
    async indexSpacesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StudyProtocolVersion>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/spaces`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StudyProtocolVersionFromJSON));
    }

    /**
     * Index
     */
    async indexSpacesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StudyProtocolVersion>> {
        const response = await this.indexSpacesGetRaw(initOverrides);
        return await response.value();
    }

}
