/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DefinedObservationResult,
  HTTPValidationError,
} from '../models/index';
import {
    DefinedObservationResultFromJSON,
    DefinedObservationResultToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface IndexSpacesSpaceIdActivitySaIdResultGetRequest {
    spaceId: string;
    saId: string;
}

/**
 * 
 */
export class DefinedObservationResultApi extends runtime.BaseAPI {

    /**
     * Index
     */
    async indexSpacesSpaceIdActivitySaIdResultGetRaw(requestParameters: IndexSpacesSpaceIdActivitySaIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DefinedObservationResult>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpacesSpaceIdActivitySaIdResultGet().'
            );
        }

        if (requestParameters['saId'] == null) {
            throw new runtime.RequiredError(
                'saId',
                'Required parameter "saId" was null or undefined when calling indexSpacesSpaceIdActivitySaIdResultGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces/{space_id}/activity/{sa_id}/result`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"sa_id"}}`, encodeURIComponent(String(requestParameters['saId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DefinedObservationResultFromJSON));
    }

    /**
     * Index
     */
    async indexSpacesSpaceIdActivitySaIdResultGet(requestParameters: IndexSpacesSpaceIdActivitySaIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DefinedObservationResult>> {
        const response = await this.indexSpacesSpaceIdActivitySaIdResultGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
