/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PerformedObservationResult,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PerformedObservationResultFromJSON,
    PerformedObservationResultToJSON,
} from '../models/index';

export interface IndexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGetRequest {
    spaceId: string;
    subjectId: string;
    obsId: string;
}

/**
 * 
 */
export class PerformedObservationResultApi extends runtime.BaseAPI {

    /**
     * Index
     */
    async indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGetRaw(requestParameters: IndexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PerformedObservationResult>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGet().'
            );
        }

        if (requestParameters['obsId'] == null) {
            throw new runtime.RequiredError(
                'obsId',
                'Required parameter "obsId" was null or undefined when calling indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces/{space_id}/subjects/{subject_id}/activity/{obs_id}/result`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));
        urlPath = urlPath.replace(`{${"obs_id"}}`, encodeURIComponent(String(requestParameters['obsId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PerformedObservationResultFromJSON));
    }

    /**
     * Index
     */
    async indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGet(requestParameters: IndexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PerformedObservationResult>> {
        const response = await this.indexSpacesSpaceIdSubjectsSubjectIdActivityObsIdResultGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
