/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BiologicEntityName,
  BiologicEntityNameData,
  HTTPValidationError,
  Person,
  PersonPatch,
  PersonPostalAddress,
  PersonPostalAddressData,
  PersonStudySubject,
  PersonTelecommunicationAddress,
  PersonTelecommunicationAddressData,
} from '../models/index';
import {
    BiologicEntityNameFromJSON,
    BiologicEntityNameToJSON,
    BiologicEntityNameDataFromJSON,
    BiologicEntityNameDataToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PersonFromJSON,
    PersonToJSON,
    PersonPatchFromJSON,
    PersonPatchToJSON,
    PersonPostalAddressFromJSON,
    PersonPostalAddressToJSON,
    PersonPostalAddressDataFromJSON,
    PersonPostalAddressDataToJSON,
    PersonStudySubjectFromJSON,
    PersonStudySubjectToJSON,
    PersonTelecommunicationAddressFromJSON,
    PersonTelecommunicationAddressToJSON,
    PersonTelecommunicationAddressDataFromJSON,
    PersonTelecommunicationAddressDataToJSON,
} from '../models/index';

export interface CreatePersonPersonIdNamePostRequest {
    personId: string;
    biologicEntityNameData: BiologicEntityNameData;
}

export interface CreatePersonPersonIdPostalAddressPostRequest {
    personId: string;
    personPostalAddressData: PersonPostalAddressData;
}

export interface CreatePersonPersonIdTelecommunicationAddressPostRequest {
    personId: string;
    personTelecommunicationAddressData: PersonTelecommunicationAddressData;
}

export interface DeletePersonPersonIdNameNameIdDeleteRequest {
    personId: string;
    nameId: string;
}

export interface DeletePersonPersonIdPostalAddressAddressIdDeleteRequest {
    personId: string;
    addressId: string;
}

export interface DeletePersonPersonIdTelecommunicationAddressAddressIdDeleteRequest {
    personId: string;
    addressId: string;
}

export interface IndexPersonPersonIdNameGetRequest {
    personId: string;
}

export interface IndexPersonPersonIdPostalAddressGetRequest {
    personId: string;
}

export interface IndexPersonPersonIdSubjectGetRequest {
    personId: string;
}

export interface IndexPersonPersonIdTelecommunicationAddressGetRequest {
    personId: string;
}

export interface ShowPersonPersonIdGetRequest {
    personId: string;
}

export interface UpdatePersonPersonIdNameNameIdPatchRequest {
    personId: string;
    nameId: string;
    biologicEntityNameData: BiologicEntityNameData;
}

export interface UpdatePersonPersonIdPatchRequest {
    personId: string;
    personPatch: PersonPatch;
}

export interface UpdatePersonPersonIdPostalAddressAddressIdPatchRequest {
    personId: string;
    addressId: string;
    personPostalAddressData: PersonPostalAddressData;
}

export interface UpdatePersonPersonIdTelecommunicationAddressAddressIdPatchRequest {
    personId: string;
    addressId: string;
    personTelecommunicationAddressData: PersonTelecommunicationAddressData;
}

/**
 * 
 */
export class PersonsApi extends runtime.BaseAPI {

    /**
     * Create
     */
    async createPersonPersonIdNamePostRaw(requestParameters: CreatePersonPersonIdNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiologicEntityName>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonPersonIdNamePost().'
            );
        }

        if (requestParameters['biologicEntityNameData'] == null) {
            throw new runtime.RequiredError(
                'biologicEntityNameData',
                'Required parameter "biologicEntityNameData" was null or undefined when calling createPersonPersonIdNamePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/name`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BiologicEntityNameDataToJSON(requestParameters['biologicEntityNameData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiologicEntityNameFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonPersonIdNamePost(requestParameters: CreatePersonPersonIdNamePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiologicEntityName> {
        const response = await this.createPersonPersonIdNamePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async createPersonPersonIdPostalAddressPostRaw(requestParameters: CreatePersonPersonIdPostalAddressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonPostalAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonPersonIdPostalAddressPost().'
            );
        }

        if (requestParameters['personPostalAddressData'] == null) {
            throw new runtime.RequiredError(
                'personPostalAddressData',
                'Required parameter "personPostalAddressData" was null or undefined when calling createPersonPersonIdPostalAddressPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/postal_address`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPostalAddressDataToJSON(requestParameters['personPostalAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonPostalAddressFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonPersonIdPostalAddressPost(requestParameters: CreatePersonPersonIdPostalAddressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonPostalAddress> {
        const response = await this.createPersonPersonIdPostalAddressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async createPersonPersonIdTelecommunicationAddressPostRaw(requestParameters: CreatePersonPersonIdTelecommunicationAddressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonTelecommunicationAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonPersonIdTelecommunicationAddressPost().'
            );
        }

        if (requestParameters['personTelecommunicationAddressData'] == null) {
            throw new runtime.RequiredError(
                'personTelecommunicationAddressData',
                'Required parameter "personTelecommunicationAddressData" was null or undefined when calling createPersonPersonIdTelecommunicationAddressPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/telecommunication_address`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonTelecommunicationAddressDataToJSON(requestParameters['personTelecommunicationAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonTelecommunicationAddressFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonPersonIdTelecommunicationAddressPost(requestParameters: CreatePersonPersonIdTelecommunicationAddressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonTelecommunicationAddress> {
        const response = await this.createPersonPersonIdTelecommunicationAddressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonPersonIdNameNameIdDeleteRaw(requestParameters: DeletePersonPersonIdNameNameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonPersonIdNameNameIdDelete().'
            );
        }

        if (requestParameters['nameId'] == null) {
            throw new runtime.RequiredError(
                'nameId',
                'Required parameter "nameId" was null or undefined when calling deletePersonPersonIdNameNameIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/name/{name_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"name_id"}}`, encodeURIComponent(String(requestParameters['nameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonPersonIdNameNameIdDelete(requestParameters: DeletePersonPersonIdNameNameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonPersonIdNameNameIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonPersonIdPostalAddressAddressIdDeleteRaw(requestParameters: DeletePersonPersonIdPostalAddressAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonPersonIdPostalAddressAddressIdDelete().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling deletePersonPersonIdPostalAddressAddressIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/postal_address/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonPersonIdPostalAddressAddressIdDelete(requestParameters: DeletePersonPersonIdPostalAddressAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonPersonIdPostalAddressAddressIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonPersonIdTelecommunicationAddressAddressIdDeleteRaw(requestParameters: DeletePersonPersonIdTelecommunicationAddressAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonPersonIdTelecommunicationAddressAddressIdDelete().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling deletePersonPersonIdTelecommunicationAddressAddressIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/telecommunication_address/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonPersonIdTelecommunicationAddressAddressIdDelete(requestParameters: DeletePersonPersonIdTelecommunicationAddressAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonPersonIdTelecommunicationAddressAddressIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonPersonIdNameGetRaw(requestParameters: IndexPersonPersonIdNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BiologicEntityName>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonPersonIdNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/name`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BiologicEntityNameFromJSON));
    }

    /**
     * Index
     */
    async indexPersonPersonIdNameGet(requestParameters: IndexPersonPersonIdNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BiologicEntityName>> {
        const response = await this.indexPersonPersonIdNameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonPersonIdPostalAddressGetRaw(requestParameters: IndexPersonPersonIdPostalAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonPostalAddress>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonPersonIdPostalAddressGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/postal_address`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonPostalAddressFromJSON));
    }

    /**
     * Index
     */
    async indexPersonPersonIdPostalAddressGet(requestParameters: IndexPersonPersonIdPostalAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonPostalAddress>> {
        const response = await this.indexPersonPersonIdPostalAddressGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonPersonIdSubjectGetRaw(requestParameters: IndexPersonPersonIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonStudySubject>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonPersonIdSubjectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/subject`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonStudySubjectFromJSON));
    }

    /**
     * Index
     */
    async indexPersonPersonIdSubjectGet(requestParameters: IndexPersonPersonIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonStudySubject>> {
        const response = await this.indexPersonPersonIdSubjectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonPersonIdTelecommunicationAddressGetRaw(requestParameters: IndexPersonPersonIdTelecommunicationAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonTelecommunicationAddress>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonPersonIdTelecommunicationAddressGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}/telecommunication_address`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonTelecommunicationAddressFromJSON));
    }

    /**
     * Index
     */
    async indexPersonPersonIdTelecommunicationAddressGet(requestParameters: IndexPersonPersonIdTelecommunicationAddressGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonTelecommunicationAddress>> {
        const response = await this.indexPersonPersonIdTelecommunicationAddressGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show
     */
    async showPersonPersonIdGetRaw(requestParameters: ShowPersonPersonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling showPersonPersonIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/person/{person_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonFromJSON(jsonValue));
    }

    /**
     * Show
     */
    async showPersonPersonIdGet(requestParameters: ShowPersonPersonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person> {
        const response = await this.showPersonPersonIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonPersonIdNameNameIdPatchRaw(requestParameters: UpdatePersonPersonIdNameNameIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiologicEntityName>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonPersonIdNameNameIdPatch().'
            );
        }

        if (requestParameters['nameId'] == null) {
            throw new runtime.RequiredError(
                'nameId',
                'Required parameter "nameId" was null or undefined when calling updatePersonPersonIdNameNameIdPatch().'
            );
        }

        if (requestParameters['biologicEntityNameData'] == null) {
            throw new runtime.RequiredError(
                'biologicEntityNameData',
                'Required parameter "biologicEntityNameData" was null or undefined when calling updatePersonPersonIdNameNameIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/name/{name_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"name_id"}}`, encodeURIComponent(String(requestParameters['nameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BiologicEntityNameDataToJSON(requestParameters['biologicEntityNameData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiologicEntityNameFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonPersonIdNameNameIdPatch(requestParameters: UpdatePersonPersonIdNameNameIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiologicEntityName> {
        const response = await this.updatePersonPersonIdNameNameIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonPersonIdPatchRaw(requestParameters: UpdatePersonPersonIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonPersonIdPatch().'
            );
        }

        if (requestParameters['personPatch'] == null) {
            throw new runtime.RequiredError(
                'personPatch',
                'Required parameter "personPatch" was null or undefined when calling updatePersonPersonIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPatchToJSON(requestParameters['personPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonPersonIdPatch(requestParameters: UpdatePersonPersonIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person> {
        const response = await this.updatePersonPersonIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonPersonIdPostalAddressAddressIdPatchRaw(requestParameters: UpdatePersonPersonIdPostalAddressAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonPostalAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonPersonIdPostalAddressAddressIdPatch().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling updatePersonPersonIdPostalAddressAddressIdPatch().'
            );
        }

        if (requestParameters['personPostalAddressData'] == null) {
            throw new runtime.RequiredError(
                'personPostalAddressData',
                'Required parameter "personPostalAddressData" was null or undefined when calling updatePersonPersonIdPostalAddressAddressIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/postal_address/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPostalAddressDataToJSON(requestParameters['personPostalAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonPostalAddressFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonPersonIdPostalAddressAddressIdPatch(requestParameters: UpdatePersonPersonIdPostalAddressAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonPostalAddress> {
        const response = await this.updatePersonPersonIdPostalAddressAddressIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonPersonIdTelecommunicationAddressAddressIdPatchRaw(requestParameters: UpdatePersonPersonIdTelecommunicationAddressAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonTelecommunicationAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonPersonIdTelecommunicationAddressAddressIdPatch().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling updatePersonPersonIdTelecommunicationAddressAddressIdPatch().'
            );
        }

        if (requestParameters['personTelecommunicationAddressData'] == null) {
            throw new runtime.RequiredError(
                'personTelecommunicationAddressData',
                'Required parameter "personTelecommunicationAddressData" was null or undefined when calling updatePersonPersonIdTelecommunicationAddressAddressIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/person/{person_id}/telecommunication_address/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonTelecommunicationAddressDataToJSON(requestParameters['personTelecommunicationAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonTelecommunicationAddressFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonPersonIdTelecommunicationAddressAddressIdPatch(requestParameters: UpdatePersonPersonIdTelecommunicationAddressAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonTelecommunicationAddress> {
        const response = await this.updatePersonPersonIdTelecommunicationAddressAddressIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
