/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BiologicEntityName,
  BiologicEntityNameData,
  HTTPValidationError,
  Person,
  PersonPatch,
  PersonPostalAddress,
  PersonPostalAddressData,
  PersonStudySubject,
  PersonTelecommunicationAddress,
  PersonTelecommunicationAddressData,
} from '../models/index';
import {
    BiologicEntityNameFromJSON,
    BiologicEntityNameToJSON,
    BiologicEntityNameDataFromJSON,
    BiologicEntityNameDataToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PersonFromJSON,
    PersonToJSON,
    PersonPatchFromJSON,
    PersonPatchToJSON,
    PersonPostalAddressFromJSON,
    PersonPostalAddressToJSON,
    PersonPostalAddressDataFromJSON,
    PersonPostalAddressDataToJSON,
    PersonStudySubjectFromJSON,
    PersonStudySubjectToJSON,
    PersonTelecommunicationAddressFromJSON,
    PersonTelecommunicationAddressToJSON,
    PersonTelecommunicationAddressDataFromJSON,
    PersonTelecommunicationAddressDataToJSON,
} from '../models/index';

export interface CreatePersonsPersonIdNamesPostRequest {
    personId: string;
    biologicEntityNameData: BiologicEntityNameData;
}

export interface CreatePersonsPersonIdPostalAddressesPostRequest {
    personId: string;
    personPostalAddressData: PersonPostalAddressData;
}

export interface CreatePersonsPersonIdTelecommunicationAddressesPostRequest {
    personId: string;
    personTelecommunicationAddressData: PersonTelecommunicationAddressData;
}

export interface DeletePersonsPersonIdNamesNameIdDeleteRequest {
    personId: string;
    nameId: string;
}

export interface DeletePersonsPersonIdPostalAddressesAddressIdDeleteRequest {
    personId: string;
    addressId: string;
}

export interface DeletePersonsPersonIdTelecommunicationAddressesAddressIdDeleteRequest {
    personId: string;
    addressId: string;
}

export interface IndexPersonsPersonIdNamesGetRequest {
    personId: string;
}

export interface IndexPersonsPersonIdPostalAddressesGetRequest {
    personId: string;
}

export interface IndexPersonsPersonIdSubjectGetRequest {
    personId: string;
}

export interface IndexPersonsPersonIdTelecommunicationAddressesGetRequest {
    personId: string;
}

export interface ShowPersonsPersonIdGetRequest {
    personId: string;
}

export interface UpdatePersonsPersonIdNamesNameIdPatchRequest {
    personId: string;
    nameId: string;
    biologicEntityNameData: BiologicEntityNameData;
}

export interface UpdatePersonsPersonIdPatchRequest {
    personId: string;
    personPatch: PersonPatch;
}

export interface UpdatePersonsPersonIdPostalAddressesAddressIdPatchRequest {
    personId: string;
    addressId: string;
    personPostalAddressData: PersonPostalAddressData;
}

export interface UpdatePersonsPersonIdTelecommunicationAddressesAddressIdPatchRequest {
    personId: string;
    addressId: string;
    personTelecommunicationAddressData: PersonTelecommunicationAddressData;
}

/**
 * 
 */
export class PersonsApi extends runtime.BaseAPI {

    /**
     * Create
     */
    async createPersonsPersonIdNamesPostRaw(requestParameters: CreatePersonsPersonIdNamesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiologicEntityName>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonsPersonIdNamesPost().'
            );
        }

        if (requestParameters['biologicEntityNameData'] == null) {
            throw new runtime.RequiredError(
                'biologicEntityNameData',
                'Required parameter "biologicEntityNameData" was null or undefined when calling createPersonsPersonIdNamesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/names`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BiologicEntityNameDataToJSON(requestParameters['biologicEntityNameData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiologicEntityNameFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonsPersonIdNamesPost(requestParameters: CreatePersonsPersonIdNamesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiologicEntityName> {
        const response = await this.createPersonsPersonIdNamesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async createPersonsPersonIdPostalAddressesPostRaw(requestParameters: CreatePersonsPersonIdPostalAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonPostalAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonsPersonIdPostalAddressesPost().'
            );
        }

        if (requestParameters['personPostalAddressData'] == null) {
            throw new runtime.RequiredError(
                'personPostalAddressData',
                'Required parameter "personPostalAddressData" was null or undefined when calling createPersonsPersonIdPostalAddressesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/postal_addresses`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPostalAddressDataToJSON(requestParameters['personPostalAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonPostalAddressFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonsPersonIdPostalAddressesPost(requestParameters: CreatePersonsPersonIdPostalAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonPostalAddress> {
        const response = await this.createPersonsPersonIdPostalAddressesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async createPersonsPersonIdTelecommunicationAddressesPostRaw(requestParameters: CreatePersonsPersonIdTelecommunicationAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonTelecommunicationAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling createPersonsPersonIdTelecommunicationAddressesPost().'
            );
        }

        if (requestParameters['personTelecommunicationAddressData'] == null) {
            throw new runtime.RequiredError(
                'personTelecommunicationAddressData',
                'Required parameter "personTelecommunicationAddressData" was null or undefined when calling createPersonsPersonIdTelecommunicationAddressesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/telecommunication_addresses`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonTelecommunicationAddressDataToJSON(requestParameters['personTelecommunicationAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonTelecommunicationAddressFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createPersonsPersonIdTelecommunicationAddressesPost(requestParameters: CreatePersonsPersonIdTelecommunicationAddressesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonTelecommunicationAddress> {
        const response = await this.createPersonsPersonIdTelecommunicationAddressesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdNamesNameIdDeleteRaw(requestParameters: DeletePersonsPersonIdNamesNameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonsPersonIdNamesNameIdDelete().'
            );
        }

        if (requestParameters['nameId'] == null) {
            throw new runtime.RequiredError(
                'nameId',
                'Required parameter "nameId" was null or undefined when calling deletePersonsPersonIdNamesNameIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/names/{name_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"name_id"}}`, encodeURIComponent(String(requestParameters['nameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdNamesNameIdDelete(requestParameters: DeletePersonsPersonIdNamesNameIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonsPersonIdNamesNameIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdPostalAddressesAddressIdDeleteRaw(requestParameters: DeletePersonsPersonIdPostalAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonsPersonIdPostalAddressesAddressIdDelete().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling deletePersonsPersonIdPostalAddressesAddressIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/postal_addresses/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdPostalAddressesAddressIdDelete(requestParameters: DeletePersonsPersonIdPostalAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonsPersonIdPostalAddressesAddressIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdTelecommunicationAddressesAddressIdDeleteRaw(requestParameters: DeletePersonsPersonIdTelecommunicationAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling deletePersonsPersonIdTelecommunicationAddressesAddressIdDelete().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling deletePersonsPersonIdTelecommunicationAddressesAddressIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/telecommunication_addresses/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete
     */
    async deletePersonsPersonIdTelecommunicationAddressesAddressIdDelete(requestParameters: DeletePersonsPersonIdTelecommunicationAddressesAddressIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deletePersonsPersonIdTelecommunicationAddressesAddressIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonsPersonIdNamesGetRaw(requestParameters: IndexPersonsPersonIdNamesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BiologicEntityName>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonsPersonIdNamesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/names`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BiologicEntityNameFromJSON));
    }

    /**
     * Index
     */
    async indexPersonsPersonIdNamesGet(requestParameters: IndexPersonsPersonIdNamesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BiologicEntityName>> {
        const response = await this.indexPersonsPersonIdNamesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonsPersonIdPostalAddressesGetRaw(requestParameters: IndexPersonsPersonIdPostalAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonPostalAddress>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonsPersonIdPostalAddressesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/postal_addresses`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonPostalAddressFromJSON));
    }

    /**
     * Index
     */
    async indexPersonsPersonIdPostalAddressesGet(requestParameters: IndexPersonsPersonIdPostalAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonPostalAddress>> {
        const response = await this.indexPersonsPersonIdPostalAddressesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonsPersonIdSubjectGetRaw(requestParameters: IndexPersonsPersonIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonStudySubject>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonsPersonIdSubjectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/subject`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonStudySubjectFromJSON));
    }

    /**
     * Index
     */
    async indexPersonsPersonIdSubjectGet(requestParameters: IndexPersonsPersonIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonStudySubject>> {
        const response = await this.indexPersonsPersonIdSubjectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexPersonsPersonIdTelecommunicationAddressesGetRaw(requestParameters: IndexPersonsPersonIdTelecommunicationAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PersonTelecommunicationAddress>>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling indexPersonsPersonIdTelecommunicationAddressesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}/telecommunication_addresses`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PersonTelecommunicationAddressFromJSON));
    }

    /**
     * Index
     */
    async indexPersonsPersonIdTelecommunicationAddressesGet(requestParameters: IndexPersonsPersonIdTelecommunicationAddressesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PersonTelecommunicationAddress>> {
        const response = await this.indexPersonsPersonIdTelecommunicationAddressesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show
     */
    async showPersonsPersonIdGetRaw(requestParameters: ShowPersonsPersonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling showPersonsPersonIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/persons/{person_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonFromJSON(jsonValue));
    }

    /**
     * Show
     */
    async showPersonsPersonIdGet(requestParameters: ShowPersonsPersonIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person> {
        const response = await this.showPersonsPersonIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonsPersonIdNamesNameIdPatchRaw(requestParameters: UpdatePersonsPersonIdNamesNameIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BiologicEntityName>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonsPersonIdNamesNameIdPatch().'
            );
        }

        if (requestParameters['nameId'] == null) {
            throw new runtime.RequiredError(
                'nameId',
                'Required parameter "nameId" was null or undefined when calling updatePersonsPersonIdNamesNameIdPatch().'
            );
        }

        if (requestParameters['biologicEntityNameData'] == null) {
            throw new runtime.RequiredError(
                'biologicEntityNameData',
                'Required parameter "biologicEntityNameData" was null or undefined when calling updatePersonsPersonIdNamesNameIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/names/{name_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"name_id"}}`, encodeURIComponent(String(requestParameters['nameId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BiologicEntityNameDataToJSON(requestParameters['biologicEntityNameData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BiologicEntityNameFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonsPersonIdNamesNameIdPatch(requestParameters: UpdatePersonsPersonIdNamesNameIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BiologicEntityName> {
        const response = await this.updatePersonsPersonIdNamesNameIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonsPersonIdPatchRaw(requestParameters: UpdatePersonsPersonIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Person>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonsPersonIdPatch().'
            );
        }

        if (requestParameters['personPatch'] == null) {
            throw new runtime.RequiredError(
                'personPatch',
                'Required parameter "personPatch" was null or undefined when calling updatePersonsPersonIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPatchToJSON(requestParameters['personPatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonsPersonIdPatch(requestParameters: UpdatePersonsPersonIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Person> {
        const response = await this.updatePersonsPersonIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonsPersonIdPostalAddressesAddressIdPatchRaw(requestParameters: UpdatePersonsPersonIdPostalAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonPostalAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonsPersonIdPostalAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling updatePersonsPersonIdPostalAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['personPostalAddressData'] == null) {
            throw new runtime.RequiredError(
                'personPostalAddressData',
                'Required parameter "personPostalAddressData" was null or undefined when calling updatePersonsPersonIdPostalAddressesAddressIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/postal_addresses/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonPostalAddressDataToJSON(requestParameters['personPostalAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonPostalAddressFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonsPersonIdPostalAddressesAddressIdPatch(requestParameters: UpdatePersonsPersonIdPostalAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonPostalAddress> {
        const response = await this.updatePersonsPersonIdPostalAddressesAddressIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updatePersonsPersonIdTelecommunicationAddressesAddressIdPatchRaw(requestParameters: UpdatePersonsPersonIdTelecommunicationAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonTelecommunicationAddress>> {
        if (requestParameters['personId'] == null) {
            throw new runtime.RequiredError(
                'personId',
                'Required parameter "personId" was null or undefined when calling updatePersonsPersonIdTelecommunicationAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['addressId'] == null) {
            throw new runtime.RequiredError(
                'addressId',
                'Required parameter "addressId" was null or undefined when calling updatePersonsPersonIdTelecommunicationAddressesAddressIdPatch().'
            );
        }

        if (requestParameters['personTelecommunicationAddressData'] == null) {
            throw new runtime.RequiredError(
                'personTelecommunicationAddressData',
                'Required parameter "personTelecommunicationAddressData" was null or undefined when calling updatePersonsPersonIdTelecommunicationAddressesAddressIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/persons/{person_id}/telecommunication_addresses/{address_id}`;
        urlPath = urlPath.replace(`{${"person_id"}}`, encodeURIComponent(String(requestParameters['personId'])));
        urlPath = urlPath.replace(`{${"address_id"}}`, encodeURIComponent(String(requestParameters['addressId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonTelecommunicationAddressDataToJSON(requestParameters['personTelecommunicationAddressData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonTelecommunicationAddressFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updatePersonsPersonIdTelecommunicationAddressesAddressIdPatch(requestParameters: UpdatePersonsPersonIdTelecommunicationAddressesAddressIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonTelecommunicationAddress> {
        const response = await this.updatePersonsPersonIdTelecommunicationAddressesAddressIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
