/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  Specimen,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SpecimenFromJSON,
    SpecimenToJSON,
} from '../models/index';

export interface IndexSpacesSpaceIdSubjectsSubjectIdSpecimenGetRequest {
    spaceId: string;
    subjectId: string;
}

/**
 * 
 */
export class SpecimenApi extends runtime.BaseAPI {

    /**
     * Index
     */
    async indexSpacesSpaceIdSubjectsSubjectIdSpecimenGetRaw(requestParameters: IndexSpacesSpaceIdSubjectsSubjectIdSpecimenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Specimen>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpacesSpaceIdSubjectsSubjectIdSpecimenGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling indexSpacesSpaceIdSubjectsSubjectIdSpecimenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/spaces/{space_id}/subjects/{subject_id}/specimen`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SpecimenFromJSON));
    }

    /**
     * Index
     */
    async indexSpacesSpaceIdSubjectsSubjectIdSpecimenGet(requestParameters: IndexSpacesSpaceIdSubjectsSubjectIdSpecimenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Specimen>> {
        const response = await this.indexSpacesSpaceIdSubjectsSubjectIdSpecimenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
