/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FoundStudySubject,
  HTTPValidationError,
  LookupStudySubject,
  NewStudySubject,
  PerformedActivity,
  PerformedActivityUnion,
  PerformedActivityUnionData,
  Specimen,
  StudySubject,
  StudySubjectData,
} from '../models/index';
import {
    FoundStudySubjectFromJSON,
    FoundStudySubjectToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LookupStudySubjectFromJSON,
    LookupStudySubjectToJSON,
    NewStudySubjectFromJSON,
    NewStudySubjectToJSON,
    PerformedActivityFromJSON,
    PerformedActivityToJSON,
    PerformedActivityUnionFromJSON,
    PerformedActivityUnionToJSON,
    PerformedActivityUnionDataFromJSON,
    PerformedActivityUnionDataToJSON,
    SpecimenFromJSON,
    SpecimenToJSON,
    StudySubjectFromJSON,
    StudySubjectToJSON,
    StudySubjectDataFromJSON,
    StudySubjectDataToJSON,
} from '../models/index';

export interface CreateSpaceSpaceIdSubjectPostRequest {
    spaceId: string;
    newStudySubject: NewStudySubject;
}

export interface CreateSpaceSpaceIdSubjectSubjectIdActivityPostRequest {
    spaceId: string;
    subjectId: string;
    performedActivityUnionData: PerformedActivityUnionData;
}

export interface IndexSpaceSpaceIdSubjectGetRequest {
    spaceId: string;
}

export interface IndexSpaceSpaceIdSubjectSubjectIdActivityGetRequest {
    spaceId: string;
    subjectId: string;
}

export interface IndexSpaceSpaceIdSubjectSubjectIdSpecimenGetRequest {
    spaceId: string;
    subjectId: string;
}

export interface LookupSpaceSpaceIdSubjectLookupPostRequest {
    spaceId: string;
    lookupStudySubject: LookupStudySubject;
}

export interface ShowSpaceSpaceIdSubjectSubjectIdActivityAIdGetRequest {
    spaceId: string;
    subjectId: string;
    aId: string;
    result?: boolean;
}

export interface ShowSpaceSpaceIdSubjectSubjectIdGetRequest {
    spaceId: string;
    subjectId: string;
}

export interface UpdateSpaceSpaceIdSubjectSubjectIdActivityAIdPatchRequest {
    spaceId: string;
    subjectId: string;
    aId: string;
    performedActivityUnionData: PerformedActivityUnionData;
}

export interface UpdateSpaceSpaceIdSubjectSubjectIdPatchRequest {
    spaceId: string;
    subjectId: string;
    studySubjectData: StudySubjectData;
}

/**
 * 
 */
export class SubjectsApi extends runtime.BaseAPI {

    /**
     * Create
     */
    async createSpaceSpaceIdSubjectPostRaw(requestParameters: CreateSpaceSpaceIdSubjectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudySubject>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling createSpaceSpaceIdSubjectPost().'
            );
        }

        if (requestParameters['newStudySubject'] == null) {
            throw new runtime.RequiredError(
                'newStudySubject',
                'Required parameter "newStudySubject" was null or undefined when calling createSpaceSpaceIdSubjectPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/space/{space_id}/subject`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewStudySubjectToJSON(requestParameters['newStudySubject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudySubjectFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createSpaceSpaceIdSubjectPost(requestParameters: CreateSpaceSpaceIdSubjectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudySubject> {
        const response = await this.createSpaceSpaceIdSubjectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create
     */
    async createSpaceSpaceIdSubjectSubjectIdActivityPostRaw(requestParameters: CreateSpaceSpaceIdSubjectSubjectIdActivityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformedActivityUnion>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling createSpaceSpaceIdSubjectSubjectIdActivityPost().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling createSpaceSpaceIdSubjectSubjectIdActivityPost().'
            );
        }

        if (requestParameters['performedActivityUnionData'] == null) {
            throw new runtime.RequiredError(
                'performedActivityUnionData',
                'Required parameter "performedActivityUnionData" was null or undefined when calling createSpaceSpaceIdSubjectSubjectIdActivityPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/space/{space_id}/subject/{subject_id}/activity`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PerformedActivityUnionDataToJSON(requestParameters['performedActivityUnionData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformedActivityUnionFromJSON(jsonValue));
    }

    /**
     * Create
     */
    async createSpaceSpaceIdSubjectSubjectIdActivityPost(requestParameters: CreateSpaceSpaceIdSubjectSubjectIdActivityPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformedActivityUnion> {
        const response = await this.createSpaceSpaceIdSubjectSubjectIdActivityPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectGetRaw(requestParameters: IndexSpaceSpaceIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StudySubject>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpaceSpaceIdSubjectGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/space/{space_id}/subject`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StudySubjectFromJSON));
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectGet(requestParameters: IndexSpaceSpaceIdSubjectGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StudySubject>> {
        const response = await this.indexSpaceSpaceIdSubjectGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectSubjectIdActivityGetRaw(requestParameters: IndexSpaceSpaceIdSubjectSubjectIdActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PerformedActivity>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpaceSpaceIdSubjectSubjectIdActivityGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling indexSpaceSpaceIdSubjectSubjectIdActivityGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/space/{space_id}/subject/{subject_id}/activity`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PerformedActivityFromJSON));
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectSubjectIdActivityGet(requestParameters: IndexSpaceSpaceIdSubjectSubjectIdActivityGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PerformedActivity>> {
        const response = await this.indexSpaceSpaceIdSubjectSubjectIdActivityGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectSubjectIdSpecimenGetRaw(requestParameters: IndexSpaceSpaceIdSubjectSubjectIdSpecimenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Specimen>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling indexSpaceSpaceIdSubjectSubjectIdSpecimenGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling indexSpaceSpaceIdSubjectSubjectIdSpecimenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/space/{space_id}/subject/{subject_id}/specimen`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SpecimenFromJSON));
    }

    /**
     * Index
     */
    async indexSpaceSpaceIdSubjectSubjectIdSpecimenGet(requestParameters: IndexSpaceSpaceIdSubjectSubjectIdSpecimenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Specimen>> {
        const response = await this.indexSpaceSpaceIdSubjectSubjectIdSpecimenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lookup
     */
    async lookupSpaceSpaceIdSubjectLookupPostRaw(requestParameters: LookupSpaceSpaceIdSubjectLookupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FoundStudySubject>>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling lookupSpaceSpaceIdSubjectLookupPost().'
            );
        }

        if (requestParameters['lookupStudySubject'] == null) {
            throw new runtime.RequiredError(
                'lookupStudySubject',
                'Required parameter "lookupStudySubject" was null or undefined when calling lookupSpaceSpaceIdSubjectLookupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/space/{space_id}/subject/lookup`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LookupStudySubjectToJSON(requestParameters['lookupStudySubject']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FoundStudySubjectFromJSON));
    }

    /**
     * Lookup
     */
    async lookupSpaceSpaceIdSubjectLookupPost(requestParameters: LookupSpaceSpaceIdSubjectLookupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FoundStudySubject>> {
        const response = await this.lookupSpaceSpaceIdSubjectLookupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show
     */
    async showSpaceSpaceIdSubjectSubjectIdActivityAIdGetRaw(requestParameters: ShowSpaceSpaceIdSubjectSubjectIdActivityAIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformedActivityUnion>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling showSpaceSpaceIdSubjectSubjectIdActivityAIdGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling showSpaceSpaceIdSubjectSubjectIdActivityAIdGet().'
            );
        }

        if (requestParameters['aId'] == null) {
            throw new runtime.RequiredError(
                'aId',
                'Required parameter "aId" was null or undefined when calling showSpaceSpaceIdSubjectSubjectIdActivityAIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['result'] != null) {
            queryParameters['result'] = requestParameters['result'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/space/{space_id}/subject/{subject_id}/activity/{a_id}`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));
        urlPath = urlPath.replace(`{${"a_id"}}`, encodeURIComponent(String(requestParameters['aId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformedActivityUnionFromJSON(jsonValue));
    }

    /**
     * Show
     */
    async showSpaceSpaceIdSubjectSubjectIdActivityAIdGet(requestParameters: ShowSpaceSpaceIdSubjectSubjectIdActivityAIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformedActivityUnion> {
        const response = await this.showSpaceSpaceIdSubjectSubjectIdActivityAIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show
     */
    async showSpaceSpaceIdSubjectSubjectIdGetRaw(requestParameters: ShowSpaceSpaceIdSubjectSubjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudySubject>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling showSpaceSpaceIdSubjectSubjectIdGet().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling showSpaceSpaceIdSubjectSubjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/space/{space_id}/subject/{subject_id}`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudySubjectFromJSON(jsonValue));
    }

    /**
     * Show
     */
    async showSpaceSpaceIdSubjectSubjectIdGet(requestParameters: ShowSpaceSpaceIdSubjectSubjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudySubject> {
        const response = await this.showSpaceSpaceIdSubjectSubjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatchRaw(requestParameters: UpdateSpaceSpaceIdSubjectSubjectIdActivityAIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PerformedActivityUnion>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatch().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatch().'
            );
        }

        if (requestParameters['aId'] == null) {
            throw new runtime.RequiredError(
                'aId',
                'Required parameter "aId" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatch().'
            );
        }

        if (requestParameters['performedActivityUnionData'] == null) {
            throw new runtime.RequiredError(
                'performedActivityUnionData',
                'Required parameter "performedActivityUnionData" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/space/{space_id}/subject/{subject_id}/activity/{a_id}`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));
        urlPath = urlPath.replace(`{${"a_id"}}`, encodeURIComponent(String(requestParameters['aId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PerformedActivityUnionDataToJSON(requestParameters['performedActivityUnionData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PerformedActivityUnionFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatch(requestParameters: UpdateSpaceSpaceIdSubjectSubjectIdActivityAIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PerformedActivityUnion> {
        const response = await this.updateSpaceSpaceIdSubjectSubjectIdActivityAIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update
     */
    async updateSpaceSpaceIdSubjectSubjectIdPatchRaw(requestParameters: UpdateSpaceSpaceIdSubjectSubjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudySubject>> {
        if (requestParameters['spaceId'] == null) {
            throw new runtime.RequiredError(
                'spaceId',
                'Required parameter "spaceId" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdPatch().'
            );
        }

        if (requestParameters['subjectId'] == null) {
            throw new runtime.RequiredError(
                'subjectId',
                'Required parameter "subjectId" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdPatch().'
            );
        }

        if (requestParameters['studySubjectData'] == null) {
            throw new runtime.RequiredError(
                'studySubjectData',
                'Required parameter "studySubjectData" was null or undefined when calling updateSpaceSpaceIdSubjectSubjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/space/{space_id}/subject/{subject_id}`;
        urlPath = urlPath.replace(`{${"space_id"}}`, encodeURIComponent(String(requestParameters['spaceId'])));
        urlPath = urlPath.replace(`{${"subject_id"}}`, encodeURIComponent(String(requestParameters['subjectId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: StudySubjectDataToJSON(requestParameters['studySubjectData']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudySubjectFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateSpaceSpaceIdSubjectSubjectIdPatch(requestParameters: UpdateSpaceSpaceIdSubjectSubjectIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudySubject> {
        const response = await this.updateSpaceSpaceIdSubjectSubjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
