/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityNameOutput } from './EntityNameOutput';
import {
    EntityNameOutputFromJSON,
    EntityNameOutputFromJSONTyped,
    EntityNameOutputToJSON,
    EntityNameOutputToJSONTyped,
} from './EntityNameOutput';
import type { AdministrativeGender } from './AdministrativeGender';
import {
    AdministrativeGenderFromJSON,
    AdministrativeGenderFromJSONTyped,
    AdministrativeGenderToJSON,
    AdministrativeGenderToJSONTyped,
} from './AdministrativeGender';

/**
 * 
 * @export
 * @interface ApiPersonPerson
 */
export interface ApiPersonPerson {
    /**
     * 
     * @type {AdministrativeGender}
     * @memberof ApiPersonPerson
     */
    administrativeGenderCode: AdministrativeGender | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiPersonPerson
     */
    birthDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiPersonPerson
     */
    deathDate: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiPersonPerson
     */
    deathDateEstimatedIndicator: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiPersonPerson
     */
    deathIndicator: boolean | null;
    /**
     * 
     * @type {EntityNameOutput}
     * @memberof ApiPersonPerson
     */
    primaryName: EntityNameOutput | null;
    /**
     * 
     * @type {string}
     * @memberof ApiPersonPerson
     */
    id: string;
}



/**
 * Check if a given object implements the ApiPersonPerson interface.
 */
export function instanceOfApiPersonPerson(value: object): value is ApiPersonPerson {
    if (!('administrativeGenderCode' in value) || value['administrativeGenderCode'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('deathDate' in value) || value['deathDate'] === undefined) return false;
    if (!('deathDateEstimatedIndicator' in value) || value['deathDateEstimatedIndicator'] === undefined) return false;
    if (!('deathIndicator' in value) || value['deathIndicator'] === undefined) return false;
    if (!('primaryName' in value) || value['primaryName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiPersonPersonFromJSON(json: any): ApiPersonPerson {
    return ApiPersonPersonFromJSONTyped(json, false);
}

export function ApiPersonPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiPersonPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'administrativeGenderCode': AdministrativeGenderFromJSON(json['administrative_gender_code']),
        'birthDate': (json['birth_date'] == null ? null : new Date(json['birth_date'])),
        'deathDate': (json['death_date'] == null ? null : new Date(json['death_date'])),
        'deathDateEstimatedIndicator': json['death_date_estimated_indicator'],
        'deathIndicator': json['death_indicator'],
        'primaryName': EntityNameOutputFromJSON(json['primary_name']),
        'id': json['id'],
    };
}

export function ApiPersonPersonToJSON(json: any): ApiPersonPerson {
    return ApiPersonPersonToJSONTyped(json, false);
}

export function ApiPersonPersonToJSONTyped(value?: ApiPersonPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'administrative_gender_code': AdministrativeGenderToJSON(value['administrativeGenderCode']),
        'birth_date': ((value['birthDate'] as any).toISOString().substring(0,10)),
        'death_date': ((value['deathDate'] as any).toISOString().substring(0,10)),
        'death_date_estimated_indicator': value['deathDateEstimatedIndicator'],
        'death_indicator': value['deathIndicator'],
        'primary_name': EntityNameOutputToJSON(value['primaryName']),
        'id': value['id'],
    };
}

