/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityName } from './EntityName';
import {
    EntityNameFromJSON,
    EntityNameFromJSONTyped,
    EntityNameToJSON,
    EntityNameToJSONTyped,
} from './EntityName';
import type { AdministrativeGender } from './AdministrativeGender';
import {
    AdministrativeGenderFromJSON,
    AdministrativeGenderFromJSONTyped,
    AdministrativeGenderToJSON,
    AdministrativeGenderToJSONTyped,
} from './AdministrativeGender';

/**
 * 
 * @export
 * @interface ApiSubjectStudySubjectPerson
 */
export interface ApiSubjectStudySubjectPerson {
    /**
     * 
     * @type {AdministrativeGender}
     * @memberof ApiSubjectStudySubjectPerson
     */
    administrativeGenderCode: AdministrativeGender | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiSubjectStudySubjectPerson
     */
    birthDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApiSubjectStudySubjectPerson
     */
    deathDate: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiSubjectStudySubjectPerson
     */
    deathDateEstimatedIndicator: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiSubjectStudySubjectPerson
     */
    deathIndicator: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ApiSubjectStudySubjectPerson
     */
    id: string;
    /**
     * 
     * @type {EntityName}
     * @memberof ApiSubjectStudySubjectPerson
     */
    primaryName: EntityName | null;
}



/**
 * Check if a given object implements the ApiSubjectStudySubjectPerson interface.
 */
export function instanceOfApiSubjectStudySubjectPerson(value: object): value is ApiSubjectStudySubjectPerson {
    if (!('administrativeGenderCode' in value) || value['administrativeGenderCode'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('deathDate' in value) || value['deathDate'] === undefined) return false;
    if (!('deathDateEstimatedIndicator' in value) || value['deathDateEstimatedIndicator'] === undefined) return false;
    if (!('deathIndicator' in value) || value['deathIndicator'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('primaryName' in value) || value['primaryName'] === undefined) return false;
    return true;
}

export function ApiSubjectStudySubjectPersonFromJSON(json: any): ApiSubjectStudySubjectPerson {
    return ApiSubjectStudySubjectPersonFromJSONTyped(json, false);
}

export function ApiSubjectStudySubjectPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSubjectStudySubjectPerson {
    if (json == null) {
        return json;
    }
    return {
        
        'administrativeGenderCode': AdministrativeGenderFromJSON(json['administrative_gender_code']),
        'birthDate': (json['birth_date'] == null ? null : new Date(json['birth_date'])),
        'deathDate': (json['death_date'] == null ? null : new Date(json['death_date'])),
        'deathDateEstimatedIndicator': json['death_date_estimated_indicator'],
        'deathIndicator': json['death_indicator'],
        'id': json['id'],
        'primaryName': EntityNameFromJSON(json['primary_name']),
    };
}

export function ApiSubjectStudySubjectPersonToJSON(json: any): ApiSubjectStudySubjectPerson {
    return ApiSubjectStudySubjectPersonToJSONTyped(json, false);
}

export function ApiSubjectStudySubjectPersonToJSONTyped(value?: ApiSubjectStudySubjectPerson | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'administrative_gender_code': AdministrativeGenderToJSON(value['administrativeGenderCode']),
        'birth_date': ((value['birthDate'] as any).toISOString().substring(0,10)),
        'death_date': ((value['deathDate'] as any).toISOString().substring(0,10)),
        'death_date_estimated_indicator': value['deathDateEstimatedIndicator'],
        'death_indicator': value['deathIndicator'],
        'id': value['id'],
        'primary_name': EntityNameToJSON(value['primaryName']),
    };
}

