/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BiologicEntityNameData
 */
export interface BiologicEntityNameData {
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    family?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    given?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    middle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    patronymic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    prefix?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicEntityNameData
     */
    suffix?: string | null;
}

/**
 * Check if a given object implements the BiologicEntityNameData interface.
 */
export function instanceOfBiologicEntityNameData(value: object): value is BiologicEntityNameData {
    return true;
}

/**
 * Check if a given object is BiologicEntityNameData JSON.
 */
export function isBiologicEntityNameDataJSON(value: object): boolean {
    return true;
}

export function BiologicEntityNameDataFromJSON(json: any): BiologicEntityNameData {
    return BiologicEntityNameDataFromJSONTyped(json, false);
}

export function BiologicEntityNameDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiologicEntityNameData {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'family': json['family'] == null ? undefined : json['family'],
        'given': json['given'] == null ? undefined : json['given'],
        'middle': json['middle'] == null ? undefined : json['middle'],
        'patronymic': json['patronymic'] == null ? undefined : json['patronymic'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
    };
}

export function BiologicEntityNameDataToJSON(json: any): BiologicEntityNameData {
    return BiologicEntityNameDataToJSONTyped(json, false);
}

export function BiologicEntityNameDataToJSONTyped(value?: BiologicEntityNameData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'family': value['family'],
        'given': value['given'],
        'middle': value['middle'],
        'patronymic': value['patronymic'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
    };
}

