/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';

/**
 * 
 * @export
 * @interface BiologicData
 */
export interface BiologicData {
    /**
     * 
     * @type {string}
     * @memberof BiologicData
     */
    type?: BiologicDataTypeEnum;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof BiologicData
     */
    code: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof BiologicData
     */
    formCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicData
     */
    description: string | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof BiologicData
     */
    typeCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof BiologicData
     */
    lotNumberText: string | null;
    /**
     * 
     * @type {Date}
     * @memberof BiologicData
     */
    expirationDate: Date | null;
}


/**
 * @export
 */
export const BiologicDataTypeEnum = {
    Biologic: 'biologic'
} as const;
export type BiologicDataTypeEnum = typeof BiologicDataTypeEnum[keyof typeof BiologicDataTypeEnum];


/**
 * Check if a given object implements the BiologicData interface.
 */
export function instanceOfBiologicData(value: object): value is BiologicData {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('formCode' in value) || value['formCode'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('typeCode' in value) || value['typeCode'] === undefined) return false;
    if (!('lotNumberText' in value) || value['lotNumberText'] === undefined) return false;
    if (!('expirationDate' in value) || value['expirationDate'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is BiologicData JSON.
 */
export function isBiologicDataJSON(value: object): boolean {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('form_code' in value) || value['form_code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('type_code' in value) || value['type_code'] === undefined) return false;
    if (!('lot_number_text' in value) || value['lot_number_text'] === undefined) return false;
    if (!('expiration_date' in value) || value['expiration_date'] === undefined) return false;
    return true;
}

export function BiologicDataFromJSON(json: any): BiologicData {
    return BiologicDataFromJSONTyped(json, false);
}

export function BiologicDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): BiologicData {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'code': ConceptDescriptorFromJSON(json['code']),
        'formCode': ConceptDescriptorFromJSON(json['form_code']),
        'description': json['description'],
        'typeCode': ConceptDescriptorFromJSON(json['type_code']),
        'lotNumberText': json['lot_number_text'],
        'expirationDate': (json['expiration_date'] == null ? null : new Date(json['expiration_date'])),
    };
}

export function BiologicDataToJSON(json: any): BiologicData {
    return BiologicDataToJSONTyped(json, false);
}

export function BiologicDataToJSONTyped(value?: BiologicData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'code': ConceptDescriptorToJSON(value['code']),
        'form_code': ConceptDescriptorToJSON(value['formCode']),
        'description': value['description'],
        'type_code': ConceptDescriptorToJSON(value['typeCode']),
        'lot_number_text': value['lotNumberText'],
        'expiration_date': value['expirationDate'] == null ? value['expirationDate'] : value['expirationDate'].toISOString().substring(0,10),
    };
}

