/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharacterString
 */
export interface CharacterString {
    /**
     * 
     * @type {string}
     * @memberof CharacterString
     */
    dataTypeName?: CharacterStringDataTypeNameEnum;
    /**
     * 
     * @type {string}
     * @memberof CharacterString
     */
    value: string;
}


/**
 * @export
 */
export const CharacterStringDataTypeNameEnum = {
    St: 'ST'
} as const;
export type CharacterStringDataTypeNameEnum = typeof CharacterStringDataTypeNameEnum[keyof typeof CharacterStringDataTypeNameEnum];


/**
 * Check if a given object implements the CharacterString interface.
 */
export function instanceOfCharacterString(value: object): value is CharacterString {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is CharacterString JSON.
 */
export function isCharacterStringJSON(value: object): boolean {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function CharacterStringFromJSON(json: any): CharacterString {
    return CharacterStringFromJSONTyped(json, false);
}

export function CharacterStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterString {
    if (json == null) {
        return json;
    }
    return {
        
        'dataTypeName': json['data_type_name'] == null ? undefined : json['data_type_name'],
        'value': json['value'],
    };
}

export function CharacterStringToJSON(json: any): CharacterString {
    return CharacterStringToJSONTyped(json, false);
}

export function CharacterStringToJSONTyped(value?: CharacterString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type_name': value['dataTypeName'],
        'value': value['value'],
    };
}

