/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConceptDescriptor
 */
export interface ConceptDescriptor {
    /**
     * 
     * @type {string}
     * @memberof ConceptDescriptor
     */
    dataType?: ConceptDescriptorDataTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ConceptDescriptor
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ConceptDescriptor
     */
    codeSystem: string;
    /**
     * 
     * @type {string}
     * @memberof ConceptDescriptor
     */
    displayName?: string | null;
}


/**
 * @export
 */
export const ConceptDescriptorDataTypeEnum = {
    Cd: 'CD'
} as const;
export type ConceptDescriptorDataTypeEnum = typeof ConceptDescriptorDataTypeEnum[keyof typeof ConceptDescriptorDataTypeEnum];


/**
 * Check if a given object implements the ConceptDescriptor interface.
 */
export function instanceOfConceptDescriptor(value: object): value is ConceptDescriptor {
    if (!('codeSystem' in value) || value['codeSystem'] === undefined) return false;
    return true;
}

export function ConceptDescriptorFromJSON(json: any): ConceptDescriptor {
    return ConceptDescriptorFromJSONTyped(json, false);
}

export function ConceptDescriptorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConceptDescriptor {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'] == null ? undefined : json['data_type'],
        'code': json['code'] == null ? undefined : json['code'],
        'codeSystem': json['code_system'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
    };
}

export function ConceptDescriptorToJSON(json: any): ConceptDescriptor {
    return ConceptDescriptorToJSONTyped(json, false);
}

export function ConceptDescriptorToJSONTyped(value?: ConceptDescriptor | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
        'code': value['code'],
        'code_system': value['codeSystem'],
        'display_name': value['displayName'],
    };
}

