/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CharacterString } from './CharacterString';
import {
    instanceOfCharacterString,
    isCharacterStringJSON,
    CharacterStringFromJSON,
    CharacterStringFromJSONTyped,
    CharacterStringToJSON,
} from './CharacterString';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    instanceOfConceptDescriptor,
    isConceptDescriptorJSON,
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
} from './ConceptDescriptor';
import type { DateTime } from './DateTime';
import {
    instanceOfDateTime,
    isDateTimeJSON,
    DateTimeFromJSON,
    DateTimeFromJSONTyped,
    DateTimeToJSON,
} from './DateTime';
import type { DateValue } from './DateValue';
import {
    instanceOfDateValue,
    isDateValueJSON,
    DateValueFromJSON,
    DateValueFromJSONTyped,
    DateValueToJSON,
} from './DateValue';
import type { PhysicalQuantity } from './PhysicalQuantity';
import {
    instanceOfPhysicalQuantity,
    isPhysicalQuantityJSON,
    PhysicalQuantityFromJSON,
    PhysicalQuantityFromJSONTyped,
    PhysicalQuantityToJSON,
} from './PhysicalQuantity';

/**
 * @type DataValue
 * 
 * @export
 */
export type DataValue = { dataTypeName: 'CD' } & ConceptDescriptor | { dataTypeName: 'PQ' } & PhysicalQuantity | string | Date;

export function DataValueFromJSON(json: any): DataValue {
    return DataValueFromJSONTyped(json, false);
}

export function DataValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataValue {
    if (json == null) {
        return json;
    }
    switch (json['data_type_name']) {
        case 'CD':
            return Object.assign({}, ConceptDescriptorFromJSONTyped(json, true), { dataTypeName: 'CD' } as const);
        case 'PQ':
            return Object.assign({}, PhysicalQuantityFromJSONTyped(json, true), { dataTypeName: 'PQ' } as const);
        case 'ST':
            return CharacterStringFromJSONTyped(json, true)["value"];
        case 'TS.DATE':
            return DateValueFromJSONTyped(json, true)["value"];
        case 'TS.DATETIME':
            return DateTimeFromJSONTyped(json, true)["value"];
        default:
            return json;
    }
}

export function DataValueToJSON(json: any): any {
    return DataValueToJSONTyped(json, false);
}

export function DataValueToJSONTyped(value?: DataValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'object') {
        if (value['dataTypeName'] == 'CD') {
            return ConceptDescriptorToJSON(Object.assign({}, value, { dataTypeName: 'CD' } as const));
        }
        if (value['dataTypeName'] == 'PQ') {
            return PhysicalQuantityToJSON(Object.assign({}, value, { dataTypeName: 'PQ' } as const));
        }
        if (value instanceof Date) {
            return DateValueToJSON(Object.assign({}, { value: value }, { dataTypeName: 'TS.DATE' } as const));
            // return DateTimeToJSON(Object.assign({}, { value: value }, { dataTypeName: 'TS.DATETIME' } as const));
        }
    } else {
        return CharacterStringToJSON(Object.assign({}, { value: value }, { dataTypeName: 'ST' } as const));
    }
}

