/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateValue
 */
export interface DateValue {
    /**
     * 
     * @type {string}
     * @memberof DateValue
     */
    dataTypeName?: DateValueDataTypeNameEnum;
    /**
     * 
     * @type {Date}
     * @memberof DateValue
     */
    value: Date;
}


/**
 * @export
 */
export const DateValueDataTypeNameEnum = {
    TsDate: 'TS.DATE'
} as const;
export type DateValueDataTypeNameEnum = typeof DateValueDataTypeNameEnum[keyof typeof DateValueDataTypeNameEnum];


/**
 * Check if a given object implements the DateValue interface.
 */
export function instanceOfDateValue(value: object): value is DateValue {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is DateValue JSON.
 */
export function isDateValueJSON(value: object): boolean {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DateValueFromJSON(json: any): DateValue {
    return DateValueFromJSONTyped(json, false);
}

export function DateValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateValue {
    if (json == null) {
        return json;
    }
    return {
        
        'dataTypeName': json['data_type_name'] == null ? undefined : json['data_type_name'],
        'value': (new Date(json['value'])),
    };
}

export function DateValueToJSON(json: any): DateValue {
    return DateValueToJSONTyped(json, false);
}

export function DateValueToJSONTyped(value?: DateValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type_name': value['dataTypeName'],
        'value': value['value'].toISOString().substring(0,10),
    };
}

