/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { DataValue } from './DataValue';
import {
    DataValueFromJSON,
    DataValueFromJSONTyped,
    DataValueToJSON,
    DataValueToJSONTyped,
} from './DataValue';
import type { DataTypeName } from './DataTypeName';
import {
    DataTypeNameFromJSON,
    DataTypeNameFromJSONTyped,
    DataTypeNameToJSON,
    DataTypeNameToJSONTyped,
} from './DataTypeName';

/**
 * 
 * @export
 * @interface DefinedObservationResult
 */
export interface DefinedObservationResult {
    /**
     * 
     * @type {DataValue}
     * @memberof DefinedObservationResult
     */
    value: DataValue | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof DefinedObservationResult
     */
    valueNegationIndicator: boolean | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedObservationResult
     */
    typeCode: ConceptDescriptor | null;
    /**
     * 
     * @type {DataTypeName}
     * @memberof DefinedObservationResult
     */
    targetType: DataTypeName;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    targetCodingSystem: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    targetUnit: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    derivationExpression: string | null;
}



/**
 * Check if a given object implements the DefinedObservationResult interface.
 */
export function instanceOfDefinedObservationResult(value: object): value is DefinedObservationResult {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('valueNegationIndicator' in value) || value['valueNegationIndicator'] === undefined) return false;
    if (!('typeCode' in value) || value['typeCode'] === undefined) return false;
    if (!('targetType' in value) || value['targetType'] === undefined) return false;
    if (!('targetCodingSystem' in value) || value['targetCodingSystem'] === undefined) return false;
    if (!('targetUnit' in value) || value['targetUnit'] === undefined) return false;
    if (!('derivationExpression' in value) || value['derivationExpression'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is DefinedObservationResult JSON.
 */
export function isDefinedObservationResultJSON(value: object): boolean {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value_negation_indicator' in value) || value['value_negation_indicator'] === undefined) return false;
    if (!('type_code' in value) || value['type_code'] === undefined) return false;
    if (!('target_type' in value) || value['target_type'] === undefined) return false;
    if (!('target_coding_system' in value) || value['target_coding_system'] === undefined) return false;
    if (!('target_unit' in value) || value['target_unit'] === undefined) return false;
    if (!('derivation_expression' in value) || value['derivation_expression'] === undefined) return false;
    return true;
}

export function DefinedObservationResultFromJSON(json: any): DefinedObservationResult {
    return DefinedObservationResultFromJSONTyped(json, false);
}

export function DefinedObservationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedObservationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'value': DataValueFromJSON(json['value']),
        'id': json['id'],
        'valueNegationIndicator': json['value_negation_indicator'],
        'typeCode': ConceptDescriptorFromJSON(json['type_code']),
        'targetType': DataTypeNameFromJSON(json['target_type']),
        'targetCodingSystem': json['target_coding_system'],
        'targetUnit': json['target_unit'],
        'derivationExpression': json['derivation_expression'],
    };
}

export function DefinedObservationResultToJSON(json: any): DefinedObservationResult {
    return DefinedObservationResultToJSONTyped(json, false);
}

export function DefinedObservationResultToJSONTyped(value?: DefinedObservationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': DataValueToJSON(value['value']),
        'id': value['id'],
        'value_negation_indicator': value['valueNegationIndicator'],
        'type_code': ConceptDescriptorToJSON(value['typeCode']),
        'target_type': DataTypeNameToJSON(value['targetType']),
        'target_coding_system': value['targetCodingSystem'],
        'target_unit': value['targetUnit'],
        'derivation_expression': value['derivationExpression'],
    };
}

