/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { Value } from './Value';
import {
    ValueFromJSON,
    ValueFromJSONTyped,
    ValueToJSON,
    ValueToJSONTyped,
} from './Value';
import type { DataTypeName } from './DataTypeName';
import {
    DataTypeNameFromJSON,
    DataTypeNameFromJSONTyped,
    DataTypeNameToJSON,
    DataTypeNameToJSONTyped,
} from './DataTypeName';

/**
 * 
 * @export
 * @interface DefinedObservationResult
 */
export interface DefinedObservationResult {
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    id: string;
    /**
     * 
     * @type {Value}
     * @memberof DefinedObservationResult
     */
    value: Value | null;
    /**
     * 
     * @type {boolean}
     * @memberof DefinedObservationResult
     */
    valueNegationIndicator: boolean | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedObservationResult
     */
    typeCode: ConceptDescriptor | null;
    /**
     * 
     * @type {DataTypeName}
     * @memberof DefinedObservationResult
     */
    targetType: DataTypeName;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    targetCodingSystem: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    targetUnit: string | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservationResult
     */
    derivationExpression: string | null;
}



/**
 * Check if a given object implements the DefinedObservationResult interface.
 */
export function instanceOfDefinedObservationResult(value: object): value is DefinedObservationResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('valueNegationIndicator' in value) || value['valueNegationIndicator'] === undefined) return false;
    if (!('typeCode' in value) || value['typeCode'] === undefined) return false;
    if (!('targetType' in value) || value['targetType'] === undefined) return false;
    if (!('targetCodingSystem' in value) || value['targetCodingSystem'] === undefined) return false;
    if (!('targetUnit' in value) || value['targetUnit'] === undefined) return false;
    if (!('derivationExpression' in value) || value['derivationExpression'] === undefined) return false;
    return true;
}

export function DefinedObservationResultFromJSON(json: any): DefinedObservationResult {
    return DefinedObservationResultFromJSONTyped(json, false);
}

export function DefinedObservationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedObservationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'value': ValueFromJSON(json['value']),
        'valueNegationIndicator': json['value_negation_indicator'],
        'typeCode': ConceptDescriptorFromJSON(json['type_code']),
        'targetType': DataTypeNameFromJSON(json['target_type']),
        'targetCodingSystem': json['target_coding_system'],
        'targetUnit': json['target_unit'],
        'derivationExpression': json['derivation_expression'],
    };
}

export function DefinedObservationResultToJSON(json: any): DefinedObservationResult {
    return DefinedObservationResultToJSONTyped(json, false);
}

export function DefinedObservationResultToJSONTyped(value?: DefinedObservationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'value': ValueToJSON(value['value']),
        'value_negation_indicator': value['valueNegationIndicator'],
        'type_code': ConceptDescriptorToJSON(value['typeCode']),
        'target_type': DataTypeNameToJSON(value['targetType']),
        'target_coding_system': value['targetCodingSystem'],
        'target_unit': value['targetUnit'],
        'derivation_expression': value['derivationExpression'],
    };
}

