/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinedObservationResult } from './DefinedObservationResult';
import {
    DefinedObservationResultFromJSON,
    DefinedObservationResultFromJSONTyped,
    DefinedObservationResultToJSON,
    DefinedObservationResultToJSONTyped,
} from './DefinedObservationResult';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';

/**
 * 
 * @export
 * @interface DefinedObservation
 */
export interface DefinedObservation {
    /**
     * 
     * @type {string}
     * @memberof DefinedObservation
     */
    id: string;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedObservation
     */
    nameCode: ConceptDescriptor;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedObservation
     */
    categoryCode: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedObservation
     */
    subcategoryCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedObservation
     */
    description: string | null;
    /**
     * 
     * @type {Array<DefinedObservationResult>}
     * @memberof DefinedObservation
     */
    producedDefinedObservationResult: Array<DefinedObservationResult>;
}

/**
 * Check if a given object implements the DefinedObservation interface.
 */
export function instanceOfDefinedObservation(value: object): value is DefinedObservation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nameCode' in value) || value['nameCode'] === undefined) return false;
    if (!('categoryCode' in value) || value['categoryCode'] === undefined) return false;
    if (!('subcategoryCode' in value) || value['subcategoryCode'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('producedDefinedObservationResult' in value) || value['producedDefinedObservationResult'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is DefinedObservation JSON.
 */
export function isDefinedObservationJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name_code' in value) || value['name_code'] === undefined) return false;
    if (!('category_code' in value) || value['category_code'] === undefined) return false;
    if (!('subcategory_code' in value) || value['subcategory_code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('produced_defined_observation_result' in value) || value['produced_defined_observation_result'] === undefined) return false;
    return true;
}

export function DefinedObservationFromJSON(json: any): DefinedObservation {
    return DefinedObservationFromJSONTyped(json, false);
}

export function DefinedObservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedObservation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nameCode': ConceptDescriptorFromJSON(json['name_code']),
        'categoryCode': ConceptDescriptorFromJSON(json['category_code']),
        'subcategoryCode': ConceptDescriptorFromJSON(json['subcategory_code']),
        'description': json['description'],
        'producedDefinedObservationResult': ((json['produced_defined_observation_result'] as Array<any>).map(DefinedObservationResultFromJSON)),
    };
}

export function DefinedObservationToJSON(json: any): DefinedObservation {
    return DefinedObservationToJSONTyped(json, false);
}

export function DefinedObservationToJSONTyped(value?: DefinedObservation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name_code': ConceptDescriptorToJSON(value['nameCode']),
        'category_code': ConceptDescriptorToJSON(value['categoryCode']),
        'subcategory_code': ConceptDescriptorToJSON(value['subcategoryCode']),
        'description': value['description'],
        'produced_defined_observation_result': ((value['producedDefinedObservationResult'] as Array<any>).map(DefinedObservationResultToJSON)),
    };
}

