/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';

/**
 * 
 * @export
 * @interface DefinedActivity
 */
export interface DefinedActivity {
    /**
     * 
     * @type {string}
     * @memberof DefinedActivity
     */
    id: string;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedActivity
     */
    nameCode: ConceptDescriptor;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedActivity
     */
    categoryCode: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof DefinedActivity
     */
    subcategoryCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof DefinedActivity
     */
    description: string | null;
}

/**
 * Check if a given object implements the DefinedActivity interface.
 */
export function instanceOfDefinedActivity(value: object): value is DefinedActivity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name_code' in value) || value['name_code'] === undefined) return false;
    if (!('category_code' in value) || value['category_code'] === undefined) return false;
    if (!('subcategory_code' in value) || value['subcategory_code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function DefinedActivityFromJSON(json: any): DefinedActivity {
    return DefinedActivityFromJSONTyped(json, false);
}

export function DefinedActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefinedActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nameCode': ConceptDescriptorFromJSON(json['name_code']),
        'categoryCode': ConceptDescriptorFromJSON(json['category_code']),
        'subcategoryCode': ConceptDescriptorFromJSON(json['subcategory_code']),
        'description': json['description'],
    };
}

export function DefinedActivityToJSON(json: any): DefinedActivity {
    return DefinedActivityToJSONTyped(json, false);
}

export function DefinedActivityToJSONTyped(value?: DefinedActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name_code': ConceptDescriptorToJSON(value['nameCode']),
        'category_code': ConceptDescriptorToJSON(value['categoryCode']),
        'subcategory_code': ConceptDescriptorToJSON(value['subcategoryCode']),
        'description': value['description'],
    };
}

