/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EntityNameOutput
 */
export interface EntityNameOutput {
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    family?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    given?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    middle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    patronymic?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    prefix?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    suffix?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EntityNameOutput
     */
    readonly label: string;
}

/**
 * Check if a given object implements the EntityNameOutput interface.
 */
export function instanceOfEntityNameOutput(value: object): value is EntityNameOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function EntityNameOutputFromJSON(json: any): EntityNameOutput {
    return EntityNameOutputFromJSONTyped(json, false);
}

export function EntityNameOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityNameOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'family': json['family'] == null ? undefined : json['family'],
        'given': json['given'] == null ? undefined : json['given'],
        'middle': json['middle'] == null ? undefined : json['middle'],
        'patronymic': json['patronymic'] == null ? undefined : json['patronymic'],
        'prefix': json['prefix'] == null ? undefined : json['prefix'],
        'suffix': json['suffix'] == null ? undefined : json['suffix'],
        'id': json['id'],
        'label': json['label'],
    };
}

export function EntityNameOutputToJSON(json: any): EntityNameOutput {
    return EntityNameOutputToJSONTyped(json, false);
}

export function EntityNameOutputToJSONTyped(value?: Omit<EntityNameOutput, 'label'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'family': value['family'],
        'given': value['given'],
        'middle': value['middle'],
        'patronymic': value['patronymic'],
        'prefix': value['prefix'],
        'suffix': value['suffix'],
        'id': value['id'],
    };
}

