/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
    PersonToJSONTyped,
} from './Person';

/**
 * 
 * @export
 * @interface FoundStudySubject
 */
export interface FoundStudySubject {
    /**
     * 
     * @type {Person}
     * @memberof FoundStudySubject
     */
    performingBiologicEntity: Person | null;
}

/**
 * Check if a given object implements the FoundStudySubject interface.
 */
export function instanceOfFoundStudySubject(value: object): value is FoundStudySubject {
    if (!('performingBiologicEntity' in value) || value['performingBiologicEntity'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is FoundStudySubject JSON.
 */
export function isFoundStudySubjectJSON(value: object): boolean {
    if (!('performing_biologic_entity' in value) || value['performing_biologic_entity'] === undefined) return false;
    return true;
}

export function FoundStudySubjectFromJSON(json: any): FoundStudySubject {
    return FoundStudySubjectFromJSONTyped(json, false);
}

export function FoundStudySubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundStudySubject {
    if (json == null) {
        return json;
    }
    return {
        
        'performingBiologicEntity': PersonFromJSON(json['performing_biologic_entity']),
    };
}

export function FoundStudySubjectToJSON(json: any): FoundStudySubject {
    return FoundStudySubjectToJSONTyped(json, false);
}

export function FoundStudySubjectToJSONTyped(value?: FoundStudySubject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'performing_biologic_entity': PersonToJSON(value['performingBiologicEntity']),
    };
}

