/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FoundStudySubject
 */
export interface FoundStudySubject {
    /**
     * 
     * @type {string}
     * @memberof FoundStudySubject
     */
    performingBiologicEntity?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FoundStudySubject
     */
    performingBiologicEntityId?: string | null;
}

/**
 * Check if a given object implements the FoundStudySubject interface.
 */
export function instanceOfFoundStudySubject(value: object): value is FoundStudySubject {
    return true;
}

export function FoundStudySubjectFromJSON(json: any): FoundStudySubject {
    return FoundStudySubjectFromJSONTyped(json, false);
}

export function FoundStudySubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoundStudySubject {
    if (json == null) {
        return json;
    }
    return {
        
        'performingBiologicEntity': json['performing_biologic_entity'] == null ? undefined : json['performing_biologic_entity'],
        'performingBiologicEntityId': json['performing_biologic_entity_id'] == null ? undefined : json['performing_biologic_entity_id'],
    };
}

export function FoundStudySubjectToJSON(json: any): FoundStudySubject {
    return FoundStudySubjectToJSONTyped(json, false);
}

export function FoundStudySubjectToJSONTyped(value?: FoundStudySubject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'performing_biologic_entity': value['performingBiologicEntity'],
        'performing_biologic_entity_id': value['performingBiologicEntityId'],
    };
}

