/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstanceIdentifier
 */
export interface InstanceIdentifier {
    /**
     * 
     * @type {string}
     * @memberof InstanceIdentifier
     */
    root: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceIdentifier
     */
    extension: string | null;
}

/**
 * Check if a given object implements the InstanceIdentifier interface.
 */
export function instanceOfInstanceIdentifier(value: object): value is InstanceIdentifier {
    if (!('root' in value) || value['root'] === undefined) return false;
    if (!('extension' in value) || value['extension'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is InstanceIdentifier JSON.
 */
export function isInstanceIdentifierJSON(value: object): boolean {
    if (!('root' in value) || value['root'] === undefined) return false;
    if (!('extension' in value) || value['extension'] === undefined) return false;
    return true;
}

export function InstanceIdentifierFromJSON(json: any): InstanceIdentifier {
    return InstanceIdentifierFromJSONTyped(json, false);
}

export function InstanceIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstanceIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'root': json['root'],
        'extension': json['extension'],
    };
}

export function InstanceIdentifierToJSON(json: any): InstanceIdentifier {
    return InstanceIdentifierToJSONTyped(json, false);
}

export function InstanceIdentifierToJSONTyped(value?: InstanceIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'root': value['root'],
        'extension': value['extension'],
    };
}

