/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegerNumber
 */
export interface IntegerNumber {
    /**
     * 
     * @type {string}
     * @memberof IntegerNumber
     */
    dataType: IntegerNumberDataTypeEnum;
}


/**
 * @export
 */
export const IntegerNumberDataTypeEnum = {
    Int: 'INT'
} as const;
export type IntegerNumberDataTypeEnum = typeof IntegerNumberDataTypeEnum[keyof typeof IntegerNumberDataTypeEnum];


/**
 * Check if a given object implements the IntegerNumber interface.
 */
export function instanceOfIntegerNumber(value: object): value is IntegerNumber {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    return true;
}

export function IntegerNumberFromJSON(json: any): IntegerNumber {
    return IntegerNumberFromJSONTyped(json, false);
}

export function IntegerNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegerNumber {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
    };
}

export function IntegerNumberToJSON(json: any): IntegerNumber {
    return IntegerNumberToJSONTyped(json, false);
}

export function IntegerNumberToJSONTyped(value?: IntegerNumber | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
    };
}

