/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiSubjectLookupStudySubjectPerson } from './ApiSubjectLookupStudySubjectPerson';
import {
    ApiSubjectLookupStudySubjectPersonFromJSON,
    ApiSubjectLookupStudySubjectPersonFromJSONTyped,
    ApiSubjectLookupStudySubjectPersonToJSON,
    ApiSubjectLookupStudySubjectPersonToJSONTyped,
} from './ApiSubjectLookupStudySubjectPerson';

/**
 * 
 * @export
 * @interface LookupStudySubject
 */
export interface LookupStudySubject {
    /**
     * 
     * @type {ApiSubjectLookupStudySubjectPerson}
     * @memberof LookupStudySubject
     */
    performingBiologicEntity?: ApiSubjectLookupStudySubjectPerson | null;
}

/**
 * Check if a given object implements the LookupStudySubject interface.
 */
export function instanceOfLookupStudySubject(value: object): value is LookupStudySubject {
    return true;
}

export function LookupStudySubjectFromJSON(json: any): LookupStudySubject {
    return LookupStudySubjectFromJSONTyped(json, false);
}

export function LookupStudySubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupStudySubject {
    if (json == null) {
        return json;
    }
    return {
        
        'performingBiologicEntity': json['performing_biologic_entity'] == null ? undefined : ApiSubjectLookupStudySubjectPersonFromJSON(json['performing_biologic_entity']),
    };
}

export function LookupStudySubjectToJSON(json: any): LookupStudySubject {
    return LookupStudySubjectToJSONTyped(json, false);
}

export function LookupStudySubjectToJSONTyped(value?: LookupStudySubject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'performing_biologic_entity': ApiSubjectLookupStudySubjectPersonToJSON(value['performingBiologicEntity']),
    };
}

