/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { MaterialIdentifier } from './MaterialIdentifier';
import {
    MaterialIdentifierFromJSON,
    MaterialIdentifierFromJSONTyped,
    MaterialIdentifierToJSON,
    MaterialIdentifierToJSONTyped,
} from './MaterialIdentifier';

/**
 * 
 * @export
 * @interface Material
 */
export interface Material {
    /**
     * 
     * @type {string}
     * @memberof Material
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Material
     */
    type?: MaterialTypeEnum;
    /**
     * 
     * @type {Array<MaterialIdentifier>}
     * @memberof Material
     */
    identifier: Array<MaterialIdentifier>;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof Material
     */
    code: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof Material
     */
    formCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof Material
     */
    description: string | null;
}


/**
 * @export
 */
export const MaterialTypeEnum = {
    Material: 'material'
} as const;
export type MaterialTypeEnum = typeof MaterialTypeEnum[keyof typeof MaterialTypeEnum];


/**
 * Check if a given object implements the Material interface.
 */
export function instanceOfMaterial(value: object): value is Material {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('formCode' in value) || value['formCode'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is Material JSON.
 */
export function isMaterialJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('identifier' in value) || value['identifier'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('form_code' in value) || value['form_code'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function MaterialFromJSON(json: any): Material {
    return MaterialFromJSONTyped(json, false);
}

export function MaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): Material {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'identifier': ((json['identifier'] as Array<any>).map(MaterialIdentifierFromJSON)),
        'code': ConceptDescriptorFromJSON(json['code']),
        'formCode': ConceptDescriptorFromJSON(json['form_code']),
        'description': json['description'],
    };
}

export function MaterialToJSON(json: any): Material {
    return MaterialToJSONTyped(json, false);
}

export function MaterialToJSONTyped(value?: Material | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'identifier': ((value['identifier'] as Array<any>).map(MaterialIdentifierToJSON)),
        'code': ConceptDescriptorToJSON(value['code']),
        'form_code': ConceptDescriptorToJSON(value['formCode']),
        'description': value['description'],
    };
}

