/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelDate
 */
export interface ModelDate {
    /**
     * 
     * @type {string}
     * @memberof ModelDate
     */
    dataType: ModelDateDataTypeEnum;
}


/**
 * @export
 */
export const ModelDateDataTypeEnum = {
    TsDate: 'TS.DATE'
} as const;
export type ModelDateDataTypeEnum = typeof ModelDateDataTypeEnum[keyof typeof ModelDateDataTypeEnum];


/**
 * Check if a given object implements the ModelDate interface.
 */
export function instanceOfModelDate(value: object): value is ModelDate {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    return true;
}

export function ModelDateFromJSON(json: any): ModelDate {
    return ModelDateFromJSONTyped(json, false);
}

export function ModelDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelDate {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
    };
}

export function ModelDateToJSON(json: any): ModelDate {
    return ModelDateToJSONTyped(json, false);
}

export function ModelDateToJSONTyped(value?: ModelDate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
    };
}

