/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationOrganizationName } from './OrganizationOrganizationName';
import {
    OrganizationOrganizationNameFromJSON,
    OrganizationOrganizationNameFromJSONTyped,
    OrganizationOrganizationNameToJSON,
    OrganizationOrganizationNameToJSONTyped,
} from './OrganizationOrganizationName';

/**
 * 
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    description: string | null;
    /**
     * 
     * @type {OrganizationOrganizationName}
     * @memberof Organization
     */
    readonly primaryName: OrganizationOrganizationName | null;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('primaryName' in value) || value['primaryName'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is Organization JSON.
 */
export function isOrganizationJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('primary_name' in value) || value['primary_name'] === undefined) return false;
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'description': json['description'],
        'primaryName': OrganizationOrganizationNameFromJSON(json['primary_name']),
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Omit<Organization, 'primary_name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'description': value['description'],
    };
}

