/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Biologic } from './Biologic';
import {
    instanceOfBiologic,
    isBiologicJSON,
    BiologicFromJSON,
    BiologicFromJSONTyped,
    BiologicToJSON,
} from './Biologic';
import type { Material } from './Material';
import {
    instanceOfMaterial,
    isMaterialJSON,
    MaterialFromJSON,
    MaterialFromJSONTyped,
    MaterialToJSON,
} from './Material';
import type { Product } from './Product';
import {
    instanceOfProduct,
    isProductJSON,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * @type PerformingMaterial
 * 
 * @export
 */
export type PerformingMaterial = { type: 'biologic' } & Biologic | { type: 'material' } & Material | { type: 'product' } & Product;

export function PerformingMaterialFromJSON(json: any): PerformingMaterial {
    return PerformingMaterialFromJSONTyped(json, false);
}

export function PerformingMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformingMaterial {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'biologic':
            return Object.assign({}, BiologicFromJSONTyped(json, true), { type: 'biologic' } as const);
        case 'material':
            return Object.assign({}, MaterialFromJSONTyped(json, true), { type: 'material' } as const);
        case 'product':
            return Object.assign({}, ProductFromJSONTyped(json, true), { type: 'product' } as const);
        default:
            return json;
    }
}

export function PerformingMaterialToJSON(json: any): any {
    return PerformingMaterialToJSONTyped(json, false);
}

export function PerformingMaterialToJSONTyped(value?: PerformingMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'biologic':
            return Object.assign({}, BiologicToJSON(value), { type: 'biologic' } as const);
        case 'material':
            return Object.assign({}, MaterialToJSON(value), { type: 'material' } as const);
        case 'product':
            return Object.assign({}, ProductToJSON(value), { type: 'product' } as const);
        default:
            return value;
    }
}

