/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformedObservationResultData } from './PerformedObservationResultData';
import {
    PerformedObservationResultDataFromJSON,
    PerformedObservationResultDataFromJSONTyped,
    PerformedObservationResultDataToJSON,
    PerformedObservationResultDataToJSONTyped,
} from './PerformedObservationResultData';
import type { IntervalPointInTime } from './IntervalPointInTime';
import {
    IntervalPointInTimeFromJSON,
    IntervalPointInTimeFromJSONTyped,
    IntervalPointInTimeToJSON,
    IntervalPointInTimeToJSONTyped,
} from './IntervalPointInTime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';

/**
 * 
 * @export
 * @interface PerformedObservationData
 */
export interface PerformedObservationData {
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationData
     */
    comment: string | null;
    /**
     * 
     * @type {IntervalPointInTime}
     * @memberof PerformedObservationData
     */
    dateRange: IntervalPointInTime | null;
    /**
     * 
     * @type {boolean}
     * @memberof PerformedObservationData
     */
    negationIndicator: boolean | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedObservationData
     */
    negationReason: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedObservationData
     */
    reasonCode: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedObservationData
     */
    statusCode: ConceptDescriptor | null;
    /**
     * 
     * @type {Date}
     * @memberof PerformedObservationData
     */
    statusDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationData
     */
    contextForStudySiteId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationData
     */
    containingEpochId: string | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationData
     */
    instantiatedDefinedActivityId: string | null;
    /**
     * 
     * @type {Array<PerformedObservationResultData>}
     * @memberof PerformedObservationData
     */
    resultedPerformedObservationResult: Array<PerformedObservationResultData>;
}

/**
 * Check if a given object implements the PerformedObservationData interface.
 */
export function instanceOfPerformedObservationData(value: object): value is PerformedObservationData {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('dateRange' in value) || value['dateRange'] === undefined) return false;
    if (!('negationIndicator' in value) || value['negationIndicator'] === undefined) return false;
    if (!('negationReason' in value) || value['negationReason'] === undefined) return false;
    if (!('reasonCode' in value) || value['reasonCode'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('statusDate' in value) || value['statusDate'] === undefined) return false;
    if (!('contextForStudySiteId' in value) || value['contextForStudySiteId'] === undefined) return false;
    if (!('containingEpochId' in value) || value['containingEpochId'] === undefined) return false;
    if (!('instantiatedDefinedActivityId' in value) || value['instantiatedDefinedActivityId'] === undefined) return false;
    if (!('resultedPerformedObservationResult' in value) || value['resultedPerformedObservationResult'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PerformedObservationData JSON.
 */
export function isPerformedObservationDataJSON(value: object): boolean {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('date_range' in value) || value['date_range'] === undefined) return false;
    if (!('negation_indicator' in value) || value['negation_indicator'] === undefined) return false;
    if (!('negation_reason' in value) || value['negation_reason'] === undefined) return false;
    if (!('reason_code' in value) || value['reason_code'] === undefined) return false;
    if (!('status_code' in value) || value['status_code'] === undefined) return false;
    if (!('status_date' in value) || value['status_date'] === undefined) return false;
    if (!('context_for_study_site_id' in value) || value['context_for_study_site_id'] === undefined) return false;
    if (!('containing_epoch_id' in value) || value['containing_epoch_id'] === undefined) return false;
    if (!('instantiated_defined_activity_id' in value) || value['instantiated_defined_activity_id'] === undefined) return false;
    if (!('resulted_performed_observation_result' in value) || value['resulted_performed_observation_result'] === undefined) return false;
    return true;
}

export function PerformedObservationDataFromJSON(json: any): PerformedObservationData {
    return PerformedObservationDataFromJSONTyped(json, false);
}

export function PerformedObservationDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformedObservationData {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
        'dateRange': IntervalPointInTimeFromJSON(json['date_range']),
        'negationIndicator': json['negation_indicator'],
        'negationReason': ConceptDescriptorFromJSON(json['negation_reason']),
        'reasonCode': ConceptDescriptorFromJSON(json['reason_code']),
        'statusCode': ConceptDescriptorFromJSON(json['status_code']),
        'statusDate': (json['status_date'] == null ? null : new Date(json['status_date'])),
        'contextForStudySiteId': json['context_for_study_site_id'],
        'containingEpochId': json['containing_epoch_id'],
        'instantiatedDefinedActivityId': json['instantiated_defined_activity_id'],
        'resultedPerformedObservationResult': ((json['resulted_performed_observation_result'] as Array<any>).map(PerformedObservationResultDataFromJSON)),
    };
}

export function PerformedObservationDataToJSON(json: any): PerformedObservationData {
    return PerformedObservationDataToJSONTyped(json, false);
}

export function PerformedObservationDataToJSONTyped(value?: PerformedObservationData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
        'date_range': IntervalPointInTimeToJSON(value['dateRange']),
        'negation_indicator': value['negationIndicator'],
        'negation_reason': ConceptDescriptorToJSON(value['negationReason']),
        'reason_code': ConceptDescriptorToJSON(value['reasonCode']),
        'status_code': ConceptDescriptorToJSON(value['statusCode']),
        'status_date': value['statusDate'] == null ? value['statusDate'] : value['statusDate'].toISOString(),
        'context_for_study_site_id': value['contextForStudySiteId'],
        'containing_epoch_id': value['containingEpochId'],
        'instantiated_defined_activity_id': value['instantiatedDefinedActivityId'],
        'resulted_performed_observation_result': ((value['resultedPerformedObservationResult'] as Array<any>).map(PerformedObservationResultDataToJSON)),
    };
}

