/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { Value } from './Value';
import {
    ValueFromJSON,
    ValueFromJSONTyped,
    ValueToJSON,
    ValueToJSONTyped,
} from './Value';
import type { DataTypeName } from './DataTypeName';
import {
    DataTypeNameFromJSON,
    DataTypeNameFromJSONTyped,
    DataTypeNameToJSON,
    DataTypeNameToJSONTyped,
} from './DataTypeName';

/**
 * 
 * @export
 * @interface PerformedObservationResult
 */
export interface PerformedObservationResult {
    /**
     * 
     * @type {Value}
     * @memberof PerformedObservationResult
     */
    value: Value | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationResult
     */
    id: string;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedObservationResult
     */
    typeCode: ConceptDescriptor | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationResult
     */
    valueNullFlavorReason: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PerformedObservationResult
     */
    baselineIndicator: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PerformedObservationResult
     */
    derivedIndicator: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof PerformedObservationResult
     */
    createdDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PerformedObservationResult
     */
    reportedDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PerformedObservationResult
     */
    comment: string | null;
    /**
     * 
     * @type {DataTypeName}
     * @memberof PerformedObservationResult
     */
    readonly valueType: DataTypeName | null;
}



/**
 * Check if a given object implements the PerformedObservationResult interface.
 */
export function instanceOfPerformedObservationResult(value: object): value is PerformedObservationResult {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('typeCode' in value) || value['typeCode'] === undefined) return false;
    if (!('valueNullFlavorReason' in value) || value['valueNullFlavorReason'] === undefined) return false;
    if (!('baselineIndicator' in value) || value['baselineIndicator'] === undefined) return false;
    if (!('derivedIndicator' in value) || value['derivedIndicator'] === undefined) return false;
    if (!('createdDate' in value) || value['createdDate'] === undefined) return false;
    if (!('reportedDate' in value) || value['reportedDate'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('valueType' in value) || value['valueType'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PerformedObservationResult JSON.
 */
export function isPerformedObservationResultJSON(value: object): boolean {
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type_code' in value) || value['type_code'] === undefined) return false;
    if (!('value_null_flavor_reason' in value) || value['value_null_flavor_reason'] === undefined) return false;
    if (!('baseline_indicator' in value) || value['baseline_indicator'] === undefined) return false;
    if (!('derived_indicator' in value) || value['derived_indicator'] === undefined) return false;
    if (!('created_date' in value) || value['created_date'] === undefined) return false;
    if (!('reported_date' in value) || value['reported_date'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('value_type' in value) || value['value_type'] === undefined) return false;
    return true;
}

export function PerformedObservationResultFromJSON(json: any): PerformedObservationResult {
    return PerformedObservationResultFromJSONTyped(json, false);
}

export function PerformedObservationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformedObservationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'value': ValueFromJSON(json['value'], json['value_type']),
        'id': json['id'],
        'typeCode': ConceptDescriptorFromJSON(json['type_code']),
        'valueNullFlavorReason': json['value_null_flavor_reason'],
        'baselineIndicator': json['baseline_indicator'],
        'derivedIndicator': json['derived_indicator'],
        'createdDate': (json['created_date'] == null ? null : new Date(json['created_date'])),
        'reportedDate': (json['reported_date'] == null ? null : new Date(json['reported_date'])),
        'comment': json['comment'],
        'valueType': DataTypeNameFromJSON(json['value_type']),
    };
}

export function PerformedObservationResultToJSON(json: any): PerformedObservationResult {
    return PerformedObservationResultToJSONTyped(json, false);
}

export function PerformedObservationResultToJSONTyped(value?: Omit<PerformedObservationResult, 'value_type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': ValueToJSON(value['value']),
        'id': value['id'],
        'type_code': ConceptDescriptorToJSON(value['typeCode']),
        'value_null_flavor_reason': value['valueNullFlavorReason'],
        'baseline_indicator': value['baselineIndicator'],
        'derived_indicator': value['derivedIndicator'],
        'created_date': value['createdDate'] == null ? value['createdDate'] : value['createdDate'].toISOString(),
        'reported_date': value['reportedDate'] == null ? value['reportedDate'] : value['reportedDate'].toISOString(),
        'comment': value['comment'],
    };
}

