/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinedActivity } from './DefinedActivity';
import {
    DefinedActivityFromJSON,
    DefinedActivityFromJSONTyped,
    DefinedActivityToJSON,
    DefinedActivityToJSONTyped,
} from './DefinedActivity';
import type { IntervalPointInTime } from './IntervalPointInTime';
import {
    IntervalPointInTimeFromJSON,
    IntervalPointInTimeFromJSONTyped,
    IntervalPointInTimeToJSON,
    IntervalPointInTimeToJSONTyped,
} from './IntervalPointInTime';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { StudySite } from './StudySite';
import {
    StudySiteFromJSON,
    StudySiteFromJSONTyped,
    StudySiteToJSON,
    StudySiteToJSONTyped,
} from './StudySite';
import type { PerformedActivityType } from './PerformedActivityType';
import {
    PerformedActivityTypeFromJSON,
    PerformedActivityTypeFromJSONTyped,
    PerformedActivityTypeToJSON,
    PerformedActivityTypeToJSONTyped,
} from './PerformedActivityType';
import type { Epoch } from './Epoch';
import {
    EpochFromJSON,
    EpochFromJSONTyped,
    EpochToJSON,
    EpochToJSONTyped,
} from './Epoch';

/**
 * 
 * @export
 * @interface PerformedActivityInfo
 */
export interface PerformedActivityInfo {
    /**
     * 
     * @type {string}
     * @memberof PerformedActivityInfo
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PerformedActivityInfo
     */
    comment: string | null;
    /**
     * 
     * @type {IntervalPointInTime}
     * @memberof PerformedActivityInfo
     */
    dateRange: IntervalPointInTime | null;
    /**
     * 
     * @type {boolean}
     * @memberof PerformedActivityInfo
     */
    negationIndicator: boolean | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedActivityInfo
     */
    negationReason: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedActivityInfo
     */
    reasonCode: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedActivityInfo
     */
    statusCode: ConceptDescriptor | null;
    /**
     * 
     * @type {Date}
     * @memberof PerformedActivityInfo
     */
    statusDate: Date | null;
    /**
     * 
     * @type {StudySite}
     * @memberof PerformedActivityInfo
     */
    contextForStudySite: StudySite | null;
    /**
     * 
     * @type {Epoch}
     * @memberof PerformedActivityInfo
     */
    containingEpoch: Epoch | null;
    /**
     * 
     * @type {DefinedActivity}
     * @memberof PerformedActivityInfo
     */
    instantiatedDefinedActivity: DefinedActivity | null;
    /**
     * 
     * @type {PerformedActivityType}
     * @memberof PerformedActivityInfo
     */
    type: PerformedActivityType;
}



/**
 * Check if a given object implements the PerformedActivityInfo interface.
 */
export function instanceOfPerformedActivityInfo(value: object): value is PerformedActivityInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('dateRange' in value) || value['dateRange'] === undefined) return false;
    if (!('negationIndicator' in value) || value['negationIndicator'] === undefined) return false;
    if (!('negationReason' in value) || value['negationReason'] === undefined) return false;
    if (!('reasonCode' in value) || value['reasonCode'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('statusDate' in value) || value['statusDate'] === undefined) return false;
    if (!('contextForStudySite' in value) || value['contextForStudySite'] === undefined) return false;
    if (!('containingEpoch' in value) || value['containingEpoch'] === undefined) return false;
    if (!('instantiatedDefinedActivity' in value) || value['instantiatedDefinedActivity'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PerformedActivityInfo JSON.
 */
export function isPerformedActivityInfoJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('date_range' in value) || value['date_range'] === undefined) return false;
    if (!('negation_indicator' in value) || value['negation_indicator'] === undefined) return false;
    if (!('negation_reason' in value) || value['negation_reason'] === undefined) return false;
    if (!('reason_code' in value) || value['reason_code'] === undefined) return false;
    if (!('status_code' in value) || value['status_code'] === undefined) return false;
    if (!('status_date' in value) || value['status_date'] === undefined) return false;
    if (!('context_for_study_site' in value) || value['context_for_study_site'] === undefined) return false;
    if (!('containing_epoch' in value) || value['containing_epoch'] === undefined) return false;
    if (!('instantiated_defined_activity' in value) || value['instantiated_defined_activity'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PerformedActivityInfoFromJSON(json: any): PerformedActivityInfo {
    return PerformedActivityInfoFromJSONTyped(json, false);
}

export function PerformedActivityInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformedActivityInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'comment': json['comment'],
        'dateRange': IntervalPointInTimeFromJSON(json['date_range']),
        'negationIndicator': json['negation_indicator'],
        'negationReason': ConceptDescriptorFromJSON(json['negation_reason']),
        'reasonCode': ConceptDescriptorFromJSON(json['reason_code']),
        'statusCode': ConceptDescriptorFromJSON(json['status_code']),
        'statusDate': (json['status_date'] == null ? null : new Date(json['status_date'])),
        'contextForStudySite': StudySiteFromJSON(json['context_for_study_site']),
        'containingEpoch': EpochFromJSON(json['containing_epoch']),
        'instantiatedDefinedActivity': DefinedActivityFromJSON(json['instantiated_defined_activity']),
        'type': PerformedActivityTypeFromJSON(json['type']),
    };
}

export function PerformedActivityInfoToJSON(json: any): PerformedActivityInfo {
    return PerformedActivityInfoToJSONTyped(json, false);
}

export function PerformedActivityInfoToJSONTyped(value?: PerformedActivityInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'comment': value['comment'],
        'date_range': IntervalPointInTimeToJSON(value['dateRange']),
        'negation_indicator': value['negationIndicator'],
        'negation_reason': ConceptDescriptorToJSON(value['negationReason']),
        'reason_code': ConceptDescriptorToJSON(value['reasonCode']),
        'status_code': ConceptDescriptorToJSON(value['statusCode']),
        'status_date': value['statusDate'] == null ? value['statusDate'] : value['statusDate'].toISOString(),
        'context_for_study_site': StudySiteToJSON(value['contextForStudySite']),
        'containing_epoch': EpochToJSON(value['containingEpoch']),
        'instantiated_defined_activity': DefinedActivityToJSON(value['instantiatedDefinedActivity']),
        'type': PerformedActivityTypeToJSON(value['type']),
    };
}

