/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BiologicData } from './BiologicData';
import {
    instanceOfBiologicData,
    isBiologicDataJSON,
    BiologicDataFromJSON,
    BiologicDataFromJSONTyped,
    BiologicDataToJSON,
} from './BiologicData';
import type { MaterialData } from './MaterialData';
import {
    instanceOfMaterialData,
    isMaterialDataJSON,
    MaterialDataFromJSON,
    MaterialDataFromJSONTyped,
    MaterialDataToJSON,
} from './MaterialData';
import type { ProductData } from './ProductData';
import {
    instanceOfProductData,
    isProductDataJSON,
    ProductDataFromJSON,
    ProductDataFromJSONTyped,
    ProductDataToJSON,
} from './ProductData';

/**
 * @type PerformingMaterialData
 * 
 * @export
 */
export type PerformingMaterialData = { type: 'biologic' } & BiologicData | { type: 'material' } & MaterialData | { type: 'product' } & ProductData;

export function PerformingMaterialDataFromJSON(json: any): PerformingMaterialData {
    return PerformingMaterialDataFromJSONTyped(json, false);
}

export function PerformingMaterialDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformingMaterialData {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'biologic':
            return Object.assign({}, BiologicDataFromJSONTyped(json, true), { type: 'biologic' } as const);
        case 'material':
            return Object.assign({}, MaterialDataFromJSONTyped(json, true), { type: 'material' } as const);
        case 'product':
            return Object.assign({}, ProductDataFromJSONTyped(json, true), { type: 'product' } as const);
        default:
            return json;
    }
}

export function PerformingMaterialDataToJSON(json: any): any {
    return PerformingMaterialDataToJSONTyped(json, false);
}

export function PerformingMaterialDataToJSONTyped(value?: PerformingMaterialData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'biologic':
            return Object.assign({}, BiologicDataToJSON(value), { type: 'biologic' } as const);
        case 'material':
            return Object.assign({}, MaterialDataToJSON(value), { type: 'material' } as const);
        case 'product':
            return Object.assign({}, ProductDataToJSON(value), { type: 'product' } as const);
        default:
            return value;
    }
}

