/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PerformedActivityData } from './PerformedActivityData';
import {
    instanceOfPerformedActivityData,
    isPerformedActivityDataJSON,
    PerformedActivityDataFromJSON,
    PerformedActivityDataFromJSONTyped,
    PerformedActivityDataToJSON,
} from './PerformedActivityData';
import type { PerformedObservationData } from './PerformedObservationData';
import {
    instanceOfPerformedObservationData,
    isPerformedObservationDataJSON,
    PerformedObservationDataFromJSON,
    PerformedObservationDataFromJSONTyped,
    PerformedObservationDataToJSON,
} from './PerformedObservationData';
import type { PerformedSpecimenCollectionData } from './PerformedSpecimenCollectionData';
import {
    instanceOfPerformedSpecimenCollectionData,
    isPerformedSpecimenCollectionDataJSON,
    PerformedSpecimenCollectionDataFromJSON,
    PerformedSpecimenCollectionDataFromJSONTyped,
    PerformedSpecimenCollectionDataToJSON,
} from './PerformedSpecimenCollectionData';

/**
 * @type PerformedActivityUnionData
 * 
 * @export
 */
export type PerformedActivityUnionData = PerformedActivityData | PerformedObservationData | PerformedSpecimenCollectionData;

export function PerformedActivityUnionDataFromJSON(json: any): PerformedActivityUnionData {
    return PerformedActivityUnionDataFromJSONTyped(json, false);
}

export function PerformedActivityUnionDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformedActivityUnionData {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (isPerformedObservationDataJSON(json)) {
        return PerformedObservationDataFromJSONTyped(json, true);
    }
    if (isPerformedSpecimenCollectionDataJSON(json)) {
        return PerformedSpecimenCollectionDataFromJSONTyped(json, true);
    }
    if (isPerformedActivityDataJSON(json)) {
        return PerformedActivityDataFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PerformedActivityUnionDataToJSON(json: any): any {
    return PerformedActivityUnionDataToJSONTyped(json, false);
}

export function PerformedActivityUnionDataToJSONTyped(value?: PerformedActivityUnionData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPerformedObservationData(value)) {
        return PerformedObservationDataToJSON(value as PerformedObservationData);
    }
    if (instanceOfPerformedSpecimenCollectionData(value)) {
        return PerformedSpecimenCollectionDataToJSON(value as PerformedSpecimenCollectionData);
    }
    if (instanceOfPerformedActivityData(value)) {
        return PerformedActivityDataToJSON(value as PerformedActivityData);
    }
    return {};
}

