/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinedActivity } from './DefinedActivity';
import {
    DefinedActivityFromJSON,
    DefinedActivityFromJSONTyped,
    DefinedActivityToJSON,
    DefinedActivityToJSONTyped,
} from './DefinedActivity';
import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
    ConceptDescriptorToJSONTyped,
} from './ConceptDescriptor';
import type { StudySite } from './StudySite';
import {
    StudySiteFromJSON,
    StudySiteFromJSONTyped,
    StudySiteToJSON,
    StudySiteToJSONTyped,
} from './StudySite';
import type { Epoch } from './Epoch';
import {
    EpochFromJSON,
    EpochFromJSONTyped,
    EpochToJSON,
    EpochToJSONTyped,
} from './Epoch';

/**
 * 
 * @export
 * @interface PerformedActivity
 */
export interface PerformedActivity {
    /**
     * 
     * @type {string}
     * @memberof PerformedActivity
     */
    id: string;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedActivity
     */
    reasonCode: ConceptDescriptor | null;
    /**
     * 
     * @type {ConceptDescriptor}
     * @memberof PerformedActivity
     */
    statusCode: ConceptDescriptor | null;
    /**
     * 
     * @type {Date}
     * @memberof PerformedActivity
     */
    statusDate: Date | null;
    /**
     * 
     * @type {StudySite}
     * @memberof PerformedActivity
     */
    contextForStudySite: StudySite | null;
    /**
     * 
     * @type {Epoch}
     * @memberof PerformedActivity
     */
    containingEpoch: Epoch | null;
    /**
     * 
     * @type {DefinedActivity}
     * @memberof PerformedActivity
     */
    instantiatedDefinedActivity: DefinedActivity | null;
}

/**
 * Check if a given object implements the PerformedActivity interface.
 */
export function instanceOfPerformedActivity(value: object): value is PerformedActivity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reasonCode' in value) || value['reasonCode'] === undefined) return false;
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('statusDate' in value) || value['statusDate'] === undefined) return false;
    if (!('contextForStudySite' in value) || value['contextForStudySite'] === undefined) return false;
    if (!('containingEpoch' in value) || value['containingEpoch'] === undefined) return false;
    if (!('instantiatedDefinedActivity' in value) || value['instantiatedDefinedActivity'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PerformedActivity JSON.
 */
export function isPerformedActivityJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('reason_code' in value) || value['reason_code'] === undefined) return false;
    if (!('status_code' in value) || value['status_code'] === undefined) return false;
    if (!('status_date' in value) || value['status_date'] === undefined) return false;
    if (!('context_for_study_site' in value) || value['context_for_study_site'] === undefined) return false;
    if (!('containing_epoch' in value) || value['containing_epoch'] === undefined) return false;
    if (!('instantiated_defined_activity' in value) || value['instantiated_defined_activity'] === undefined) return false;
    return true;
}

export function PerformedActivityFromJSON(json: any): PerformedActivity {
    return PerformedActivityFromJSONTyped(json, false);
}

export function PerformedActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PerformedActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'reasonCode': ConceptDescriptorFromJSON(json['reason_code']),
        'statusCode': ConceptDescriptorFromJSON(json['status_code']),
        'statusDate': (json['status_date'] == null ? null : new Date(json['status_date'])),
        'contextForStudySite': StudySiteFromJSON(json['context_for_study_site']),
        'containingEpoch': EpochFromJSON(json['containing_epoch']),
        'instantiatedDefinedActivity': DefinedActivityFromJSON(json['instantiated_defined_activity']),
    };
}

export function PerformedActivityToJSON(json: any): PerformedActivity {
    return PerformedActivityToJSONTyped(json, false);
}

export function PerformedActivityToJSONTyped(value?: PerformedActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'reason_code': ConceptDescriptorToJSON(value['reasonCode']),
        'status_code': ConceptDescriptorToJSON(value['statusCode']),
        'status_date': value['statusDate'] == null ? value['statusDate'] : value['statusDate'].toISOString(),
        'context_for_study_site': StudySiteToJSON(value['contextForStudySite']),
        'containing_epoch': EpochToJSON(value['containingEpoch']),
        'instantiated_defined_activity': DefinedActivityToJSON(value['instantiatedDefinedActivity']),
    };
}

