/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonPostalAddressData
 */
export interface PersonPostalAddressData {
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    building?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    municipality?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddressData
     */
    zip?: string | null;
}

/**
 * Check if a given object implements the PersonPostalAddressData interface.
 */
export function instanceOfPersonPostalAddressData(value: object): value is PersonPostalAddressData {
    return true;
}

/**
 * Check if a given object is PersonPostalAddressData JSON.
 */
export function isPersonPostalAddressDataJSON(value: object): boolean {
    return true;
}

export function PersonPostalAddressDataFromJSON(json: any): PersonPostalAddressData {
    return PersonPostalAddressDataFromJSONTyped(json, false);
}

export function PersonPostalAddressDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonPostalAddressData {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'street': json['street'] == null ? undefined : json['street'],
        'building': json['building'] == null ? undefined : json['building'],
        'country': json['country'] == null ? undefined : json['country'],
        'municipality': json['municipality'] == null ? undefined : json['municipality'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
    };
}

export function PersonPostalAddressDataToJSON(json: any): PersonPostalAddressData {
    return PersonPostalAddressDataToJSONTyped(json, false);
}

export function PersonPostalAddressDataToJSONTyped(value?: PersonPostalAddressData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'street': value['street'],
        'building': value['building'],
        'country': value['country'],
        'municipality': value['municipality'],
        'state': value['state'],
        'zip': value['zip'],
    };
}

