/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdministrativeGender } from './AdministrativeGender';
import {
    AdministrativeGenderFromJSON,
    AdministrativeGenderFromJSONTyped,
    AdministrativeGenderToJSON,
    AdministrativeGenderToJSONTyped,
} from './AdministrativeGender';

/**
 * 
 * @export
 * @interface PersonPatch
 */
export interface PersonPatch {
    /**
     * 
     * @type {AdministrativeGender}
     * @memberof PersonPatch
     */
    administrativeGenderCode: AdministrativeGender | null;
    /**
     * 
     * @type {Date}
     * @memberof PersonPatch
     */
    birthDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PersonPatch
     */
    deathDate: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof PersonPatch
     */
    deathDateEstimatedIndicator: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof PersonPatch
     */
    deathIndicator: boolean | null;
}



/**
 * Check if a given object implements the PersonPatch interface.
 */
export function instanceOfPersonPatch(value: object): value is PersonPatch {
    if (!('administrativeGenderCode' in value) || value['administrativeGenderCode'] === undefined) return false;
    if (!('birthDate' in value) || value['birthDate'] === undefined) return false;
    if (!('deathDate' in value) || value['deathDate'] === undefined) return false;
    if (!('deathDateEstimatedIndicator' in value) || value['deathDateEstimatedIndicator'] === undefined) return false;
    if (!('deathIndicator' in value) || value['deathIndicator'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PersonPatch JSON.
 */
export function isPersonPatchJSON(value: object): boolean {
    if (!('administrative_gender_code' in value) || value['administrative_gender_code'] === undefined) return false;
    if (!('birth_date' in value) || value['birth_date'] === undefined) return false;
    if (!('death_date' in value) || value['death_date'] === undefined) return false;
    if (!('death_date_estimated_indicator' in value) || value['death_date_estimated_indicator'] === undefined) return false;
    if (!('death_indicator' in value) || value['death_indicator'] === undefined) return false;
    return true;
}

export function PersonPatchFromJSON(json: any): PersonPatch {
    return PersonPatchFromJSONTyped(json, false);
}

export function PersonPatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonPatch {
    if (json == null) {
        return json;
    }
    return {
        
        'administrativeGenderCode': AdministrativeGenderFromJSON(json['administrative_gender_code']),
        'birthDate': (json['birth_date'] == null ? null : new Date(json['birth_date'])),
        'deathDate': (json['death_date'] == null ? null : new Date(json['death_date'])),
        'deathDateEstimatedIndicator': json['death_date_estimated_indicator'],
        'deathIndicator': json['death_indicator'],
    };
}

export function PersonPatchToJSON(json: any): PersonPatch {
    return PersonPatchToJSONTyped(json, false);
}

export function PersonPatchToJSONTyped(value?: PersonPatch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'administrative_gender_code': AdministrativeGenderToJSON(value['administrativeGenderCode']),
        'birth_date': value['birthDate'] == null ? value['birthDate'] : value['birthDate'].toISOString().substring(0,10),
        'death_date': value['deathDate'] == null ? value['deathDate'] : value['deathDate'].toISOString().substring(0,10),
        'death_date_estimated_indicator': value['deathDateEstimatedIndicator'],
        'death_indicator': value['deathIndicator'],
    };
}

