/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TelecommunicationAddressUse } from './TelecommunicationAddressUse';
import {
    TelecommunicationAddressUseFromJSON,
    TelecommunicationAddressUseFromJSONTyped,
    TelecommunicationAddressUseToJSON,
    TelecommunicationAddressUseToJSONTyped,
} from './TelecommunicationAddressUse';
import type { URLScheme } from './URLScheme';
import {
    URLSchemeFromJSON,
    URLSchemeFromJSONTyped,
    URLSchemeToJSON,
    URLSchemeToJSONTyped,
} from './URLScheme';

/**
 * 
 * @export
 * @interface PersonTelecommunicationAddress
 */
export interface PersonTelecommunicationAddress {
    /**
     * 
     * @type {TelecommunicationAddressUse}
     * @memberof PersonTelecommunicationAddress
     */
    use?: TelecommunicationAddressUse | null;
    /**
     * 
     * @type {URLScheme}
     * @memberof PersonTelecommunicationAddress
     */
    scheme?: URLScheme | null;
    /**
     * 
     * @type {string}
     * @memberof PersonTelecommunicationAddress
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonTelecommunicationAddress
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PersonTelecommunicationAddress
     */
    readonly label: string;
}



/**
 * Check if a given object implements the PersonTelecommunicationAddress interface.
 */
export function instanceOfPersonTelecommunicationAddress(value: object): value is PersonTelecommunicationAddress {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PersonTelecommunicationAddress JSON.
 */
export function isPersonTelecommunicationAddressJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function PersonTelecommunicationAddressFromJSON(json: any): PersonTelecommunicationAddress {
    return PersonTelecommunicationAddressFromJSONTyped(json, false);
}

export function PersonTelecommunicationAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonTelecommunicationAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : TelecommunicationAddressUseFromJSON(json['use']),
        'scheme': json['scheme'] == null ? undefined : URLSchemeFromJSON(json['scheme']),
        'address': json['address'] == null ? undefined : json['address'],
        'id': json['id'],
        'label': json['label'],
    };
}

export function PersonTelecommunicationAddressToJSON(json: any): PersonTelecommunicationAddress {
    return PersonTelecommunicationAddressToJSONTyped(json, false);
}

export function PersonTelecommunicationAddressToJSONTyped(value?: Omit<PersonTelecommunicationAddress, 'label'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': TelecommunicationAddressUseToJSON(value['use']),
        'scheme': URLSchemeToJSON(value['scheme']),
        'address': value['address'],
        'id': value['id'],
    };
}

