/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonPostalAddress
 */
export interface PersonPostalAddress {
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    street?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    building?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    municipality?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    zip?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PersonPostalAddress
     */
    readonly label: string;
}

/**
 * Check if a given object implements the PersonPostalAddress interface.
 */
export function instanceOfPersonPostalAddress(value: object): value is PersonPostalAddress {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is PersonPostalAddress JSON.
 */
export function isPersonPostalAddressJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function PersonPostalAddressFromJSON(json: any): PersonPostalAddress {
    return PersonPostalAddressFromJSONTyped(json, false);
}

export function PersonPostalAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonPostalAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'street': json['street'] == null ? undefined : json['street'],
        'building': json['building'] == null ? undefined : json['building'],
        'country': json['country'] == null ? undefined : json['country'],
        'municipality': json['municipality'] == null ? undefined : json['municipality'],
        'state': json['state'] == null ? undefined : json['state'],
        'zip': json['zip'] == null ? undefined : json['zip'],
        'id': json['id'],
        'label': json['label'],
    };
}

export function PersonPostalAddressToJSON(json: any): PersonPostalAddress {
    return PersonPostalAddressToJSONTyped(json, false);
}

export function PersonPostalAddressToJSONTyped(value?: Omit<PersonPostalAddress, 'label'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'street': value['street'],
        'building': value['building'],
        'country': value['country'],
        'municipality': value['municipality'],
        'state': value['state'],
        'zip': value['zip'],
        'id': value['id'],
    };
}

