/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PointInTime
 */
export interface PointInTime {
    /**
     * 
     * @type {string}
     * @memberof PointInTime
     */
    dataType: PointInTimeDataTypeEnum;
}


/**
 * @export
 */
export const PointInTimeDataTypeEnum = {
    Ts: 'TS'
} as const;
export type PointInTimeDataTypeEnum = typeof PointInTimeDataTypeEnum[keyof typeof PointInTimeDataTypeEnum];


/**
 * Check if a given object implements the PointInTime interface.
 */
export function instanceOfPointInTime(value: object): value is PointInTime {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    return true;
}

export function PointInTimeFromJSON(json: any): PointInTime {
    return PointInTimeFromJSONTyped(json, false);
}

export function PointInTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointInTime {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
    };
}

export function PointInTimeToJSON(json: any): PointInTime {
    return PointInTimeToJSONTyped(json, false);
}

export function PointInTimeToJSONTyped(value?: PointInTime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
    };
}

