/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PerformingMaterialData } from './PerformingMaterialData';
import {
    PerformingMaterialDataFromJSON,
    PerformingMaterialDataFromJSONTyped,
    PerformingMaterialDataToJSON,
    PerformingMaterialDataToJSONTyped,
} from './PerformingMaterialData';

/**
 * 
 * @export
 * @interface ProducedSpecimenData
 */
export interface ProducedSpecimenData {
    /**
     * 
     * @type {string}
     * @memberof ProducedSpecimenData
     */
    id?: string | null;
    /**
     * 
     * @type {PerformingMaterialData}
     * @memberof ProducedSpecimenData
     */
    performingMaterial: PerformingMaterialData;
}

/**
 * Check if a given object implements the ProducedSpecimenData interface.
 */
export function instanceOfProducedSpecimenData(value: object): value is ProducedSpecimenData {
    if (!('performingMaterial' in value) || value['performingMaterial'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is ProducedSpecimenData JSON.
 */
export function isProducedSpecimenDataJSON(value: object): boolean {
    if (!('performing_material' in value) || value['performing_material'] === undefined) return false;
    return true;
}

export function ProducedSpecimenDataFromJSON(json: any): ProducedSpecimenData {
    return ProducedSpecimenDataFromJSONTyped(json, false);
}

export function ProducedSpecimenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProducedSpecimenData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'performingMaterial': PerformingMaterialDataFromJSON(json['performing_material']),
    };
}

export function ProducedSpecimenDataToJSON(json: any): ProducedSpecimenData {
    return ProducedSpecimenDataToJSONTyped(json, false);
}

export function ProducedSpecimenDataToJSONTyped(value?: ProducedSpecimenData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'performing_material': PerformingMaterialDataToJSON(value['performingMaterial']),
    };
}

