/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Quantity
 */
export interface Quantity {
    /**
     * 
     * @type {string}
     * @memberof Quantity
     */
    dataType: QuantityDataTypeEnum;
}


/**
 * @export
 */
export const QuantityDataTypeEnum = {
    Qty: 'QTY'
} as const;
export type QuantityDataTypeEnum = typeof QuantityDataTypeEnum[keyof typeof QuantityDataTypeEnum];


/**
 * Check if a given object implements the Quantity interface.
 */
export function instanceOfQuantity(value: object): value is Quantity {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    return true;
}

export function QuantityFromJSON(json: any): Quantity {
    return QuantityFromJSONTyped(json, false);
}

export function QuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quantity {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
    };
}

export function QuantityToJSON(json: any): Quantity {
    return QuantityToJSONTyped(json, false);
}

export function QuantityToJSONTyped(value?: Quantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
    };
}

