/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DefinedActivity } from './DefinedActivity';
import {
    instanceOfDefinedActivity,
    DefinedActivityFromJSON,
    DefinedActivityFromJSONTyped,
    DefinedActivityToJSON,
} from './DefinedActivity';
import type { DefinedObservation } from './DefinedObservation';
import {
    instanceOfDefinedObservation,
    DefinedObservationFromJSON,
    DefinedObservationFromJSONTyped,
    DefinedObservationToJSON,
} from './DefinedObservation';

/**
 * @type ResponseShowDefinedActivityAIdGet
 * 
 * @export
 */
export type ResponseShowDefinedActivityAIdGet = DefinedActivity | DefinedObservation;

export function ResponseShowDefinedActivityAIdGetFromJSON(json: any): ResponseShowDefinedActivityAIdGet {
    return ResponseShowDefinedActivityAIdGetFromJSONTyped(json, false);
}

export function ResponseShowDefinedActivityAIdGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseShowDefinedActivityAIdGet {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfDefinedObservation(json)) {
        return DefinedObservationFromJSONTyped(json, true);
    }
    if (instanceOfDefinedActivity(json)) {
        return DefinedActivityFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ResponseShowDefinedActivityAIdGetToJSON(json: any): any {
    return ResponseShowDefinedActivityAIdGetToJSONTyped(json, false);
}

export function ResponseShowDefinedActivityAIdGetToJSONTyped(value?: ResponseShowDefinedActivityAIdGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfDefinedActivity(value)) {
        return DefinedActivityToJSON(value as DefinedActivity);
    }
    if (instanceOfDefinedObservation(value)) {
        return DefinedObservationToJSON(value as DefinedObservation);
    }
    return {};
}

