/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudySite
 */
export interface StudySite {
    /**
     * 
     * @type {string}
     * @memberof StudySite
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StudySite
     */
    readonly label: string;
}

/**
 * Check if a given object implements the StudySite interface.
 */
export function instanceOfStudySite(value: object): value is StudySite {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function StudySiteFromJSON(json: any): StudySite {
    return StudySiteFromJSONTyped(json, false);
}

export function StudySiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudySite {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
    };
}

export function StudySiteToJSON(json: any): StudySite {
    return StudySiteToJSONTyped(json, false);
}

export function StudySiteToJSONTyped(value?: Omit<StudySite, 'label'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

