/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudyProtocolVersion } from './StudyProtocolVersion';
import {
    StudyProtocolVersionFromJSON,
    StudyProtocolVersionFromJSONTyped,
    StudyProtocolVersionToJSON,
    StudyProtocolVersionToJSONTyped,
} from './StudyProtocolVersion';
import type { StudySite } from './StudySite';
import {
    StudySiteFromJSON,
    StudySiteFromJSONTyped,
    StudySiteToJSON,
    StudySiteToJSONTyped,
} from './StudySite';

/**
 * 
 * @export
 * @interface StudySiteProtocolVersionRelationship
 */
export interface StudySiteProtocolVersionRelationship {
    /**
     * 
     * @type {string}
     * @memberof StudySiteProtocolVersionRelationship
     */
    id: string;
    /**
     * 
     * @type {StudySite}
     * @memberof StudySiteProtocolVersionRelationship
     */
    executingStudySite: StudySite;
    /**
     * 
     * @type {StudyProtocolVersion}
     * @memberof StudySiteProtocolVersionRelationship
     */
    executedStudyProtocolVersion: StudyProtocolVersion;
}

/**
 * Check if a given object implements the StudySiteProtocolVersionRelationship interface.
 */
export function instanceOfStudySiteProtocolVersionRelationship(value: object): value is StudySiteProtocolVersionRelationship {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('executingStudySite' in value) || value['executingStudySite'] === undefined) return false;
    if (!('executedStudyProtocolVersion' in value) || value['executedStudyProtocolVersion'] === undefined) return false;
    return true;
}

/**
 * Check if a given object is StudySiteProtocolVersionRelationship JSON.
 */
export function isStudySiteProtocolVersionRelationshipJSON(value: object): boolean {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('executing_study_site' in value) || value['executing_study_site'] === undefined) return false;
    if (!('executed_study_protocol_version' in value) || value['executed_study_protocol_version'] === undefined) return false;
    return true;
}

export function StudySiteProtocolVersionRelationshipFromJSON(json: any): StudySiteProtocolVersionRelationship {
    return StudySiteProtocolVersionRelationshipFromJSONTyped(json, false);
}

export function StudySiteProtocolVersionRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudySiteProtocolVersionRelationship {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'executingStudySite': StudySiteFromJSON(json['executing_study_site']),
        'executedStudyProtocolVersion': StudyProtocolVersionFromJSON(json['executed_study_protocol_version']),
    };
}

export function StudySiteProtocolVersionRelationshipToJSON(json: any): StudySiteProtocolVersionRelationship {
    return StudySiteProtocolVersionRelationshipToJSONTyped(json, false);
}

export function StudySiteProtocolVersionRelationshipToJSONTyped(value?: StudySiteProtocolVersionRelationship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'executing_study_site': StudySiteToJSON(value['executingStudySite']),
        'executed_study_protocol_version': StudyProtocolVersionToJSON(value['executedStudyProtocolVersion']),
    };
}

