/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudyProtocolVersion
 */
export interface StudyProtocolVersion {
    /**
     * 
     * @type {string}
     * @memberof StudyProtocolVersion
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StudyProtocolVersion
     */
    readonly label: string | null;
}

/**
 * Check if a given object implements the StudyProtocolVersion interface.
 */
export function instanceOfStudyProtocolVersion(value: object): value is StudyProtocolVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function StudyProtocolVersionFromJSON(json: any): StudyProtocolVersion {
    return StudyProtocolVersionFromJSONTyped(json, false);
}

export function StudyProtocolVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyProtocolVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'label': json['label'],
    };
}

export function StudyProtocolVersionToJSON(json: any): StudyProtocolVersion {
    return StudyProtocolVersionToJSONTyped(json, false);
}

export function StudyProtocolVersionToJSONTyped(value?: Omit<StudyProtocolVersion, 'label'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

