/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
    StatusToJSONTyped,
} from './Status';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
    OrganizationToJSONTyped,
} from './Organization';
import type { ApiSubjectStudySubjectPerson } from './ApiSubjectStudySubjectPerson';
import {
    ApiSubjectStudySubjectPersonFromJSON,
    ApiSubjectStudySubjectPersonFromJSONTyped,
    ApiSubjectStudySubjectPersonToJSON,
    ApiSubjectStudySubjectPersonToJSONTyped,
} from './ApiSubjectStudySubjectPerson';

/**
 * 
 * @export
 * @interface StudySubject
 */
export interface StudySubject {
    /**
     * 
     * @type {string}
     * @memberof StudySubject
     */
    id: string;
    /**
     * 
     * @type {Status}
     * @memberof StudySubject
     */
    status: Status | null;
    /**
     * 
     * @type {Date}
     * @memberof StudySubject
     */
    statusDate: Date | null;
    /**
     * 
     * @type {ApiSubjectStudySubjectPerson}
     * @memberof StudySubject
     */
    performingBiologicEntity: ApiSubjectStudySubjectPerson | null;
    /**
     * 
     * @type {Organization}
     * @memberof StudySubject
     */
    performingOrganization: Organization | null;
}



/**
 * Check if a given object implements the StudySubject interface.
 */
export function instanceOfStudySubject(value: object): value is StudySubject {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusDate' in value) || value['statusDate'] === undefined) return false;
    if (!('performingBiologicEntity' in value) || value['performingBiologicEntity'] === undefined) return false;
    if (!('performingOrganization' in value) || value['performingOrganization'] === undefined) return false;
    return true;
}

export function StudySubjectFromJSON(json: any): StudySubject {
    return StudySubjectFromJSONTyped(json, false);
}

export function StudySubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudySubject {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': StatusFromJSON(json['status']),
        'statusDate': (json['status_date'] == null ? null : new Date(json['status_date'])),
        'performingBiologicEntity': ApiSubjectStudySubjectPersonFromJSON(json['performing_biologic_entity']),
        'performingOrganization': OrganizationFromJSON(json['performing_organization']),
    };
}

export function StudySubjectToJSON(json: any): StudySubject {
    return StudySubjectToJSONTyped(json, false);
}

export function StudySubjectToJSONTyped(value?: StudySubject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': StatusToJSON(value['status']),
        'status_date': ((value['statusDate'] as any).toISOString()),
        'performing_biologic_entity': ApiSubjectStudySubjectPersonToJSON(value['performingBiologicEntity']),
        'performing_organization': OrganizationToJSON(value['performingOrganization']),
    };
}

