/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DefinedActivity } from './DefinedActivity';
import {
    DefinedActivityFromJSON,
    DefinedActivityFromJSONTyped,
    DefinedActivityToJSON,
    DefinedActivityToJSONTyped,
} from './DefinedActivity';

/**
 * 
 * @export
 * @interface StudyActivity
 */
export interface StudyActivity {
    /**
     * 
     * @type {string}
     * @memberof StudyActivity
     */
    id: string;
    /**
     * 
     * @type {DefinedActivity}
     * @memberof StudyActivity
     */
    usedDefinedActivity: DefinedActivity;
}

/**
 * Check if a given object implements the StudyActivity interface.
 */
export function instanceOfStudyActivity(value: object): value is StudyActivity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('usedDefinedActivity' in value) || value['usedDefinedActivity'] === undefined) return false;
    return true;
}

export function StudyActivityFromJSON(json: any): StudyActivity {
    return StudyActivityFromJSONTyped(json, false);
}

export function StudyActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudyActivity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'usedDefinedActivity': DefinedActivityFromJSON(json['used_defined_activity']),
    };
}

export function StudyActivityToJSON(json: any): StudyActivity {
    return StudyActivityToJSONTyped(json, false);
}

export function StudyActivityToJSONTyped(value?: StudyActivity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'used_defined_activity': DefinedActivityToJSON(value['usedDefinedActivity']),
    };
}

