/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TelecommunicationAddressData
 */
export interface TelecommunicationAddressData {
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddressData
     */
    use?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddressData
     */
    scheme?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TelecommunicationAddressData
     */
    address?: string | null;
}

/**
 * Check if a given object implements the TelecommunicationAddressData interface.
 */
export function instanceOfTelecommunicationAddressData(value: object): value is TelecommunicationAddressData {
    return true;
}

export function TelecommunicationAddressDataFromJSON(json: any): TelecommunicationAddressData {
    return TelecommunicationAddressDataFromJSONTyped(json, false);
}

export function TelecommunicationAddressDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelecommunicationAddressData {
    if (json == null) {
        return json;
    }
    return {
        
        'use': json['use'] == null ? undefined : json['use'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function TelecommunicationAddressDataToJSON(json: any): TelecommunicationAddressData {
    return TelecommunicationAddressDataToJSONTyped(json, false);
}

export function TelecommunicationAddressDataToJSONTyped(value?: TelecommunicationAddressData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'use': value['use'],
        'scheme': value['scheme'],
        'address': value['address'],
    };
}

