/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TelecommunicationAddressUse = {
    H: 'H',
    Hp: 'HP',
    Hv: 'HV',
    Wp: 'WP',
    Dir: 'DIR',
    Pub: 'PUB',
    Bad: 'BAD',
    Tmp: 'TMP',
    As: 'AS',
    Ec: 'EC',
    Mc: 'MC',
    Pg: 'PG'
} as const;
export type TelecommunicationAddressUse = typeof TelecommunicationAddressUse[keyof typeof TelecommunicationAddressUse];


export function instanceOfTelecommunicationAddressUse(value: any): boolean {
    for (const key in TelecommunicationAddressUse) {
        if (Object.prototype.hasOwnProperty.call(TelecommunicationAddressUse, key)) {
            if (TelecommunicationAddressUse[key as keyof typeof TelecommunicationAddressUse] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TelecommunicationAddressUseFromJSON(json: any): TelecommunicationAddressUse {
    return TelecommunicationAddressUseFromJSONTyped(json, false);
}

export function TelecommunicationAddressUseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelecommunicationAddressUse {
    return json as TelecommunicationAddressUse;
}

export function TelecommunicationAddressUseToJSON(value?: TelecommunicationAddressUse | null): any {
    return value as any;
}

export function TelecommunicationAddressUseToJSONTyped(value: any, ignoreDiscriminator: boolean): TelecommunicationAddressUse {
    return value as TelecommunicationAddressUse;
}

