/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConceptDescriptor } from './ConceptDescriptor';
import {
    instanceOfConceptDescriptor,
    isConceptDescriptorJSON,
    ConceptDescriptorFromJSON,
    ConceptDescriptorFromJSONTyped,
    ConceptDescriptorToJSON,
} from './ConceptDescriptor';
import { DataTypeName } from './DataTypeName';
import type { PhysicalQuantity } from './PhysicalQuantity';
import {
    instanceOfPhysicalQuantity,
    isPhysicalQuantityJSON,
    PhysicalQuantityFromJSON,
    PhysicalQuantityFromJSONTyped,
    PhysicalQuantityToJSON,
} from './PhysicalQuantity';

/**
 * @type Value
 * 
 * @export
 */
export type Value = ConceptDescriptor | Date | PhysicalQuantity | string;

export function ValueFromJSON(json: any, type: DataTypeName): Value {
    return ValueFromJSONTyped(json, type, false);
}

export function ValueFromJSONTyped(json: any, type: DataTypeName, ignoreDiscriminator: boolean): Value {
    if (json == null) {
        return json;
    }
    switch (type) {
        case DataTypeName.Cd:
            return ConceptDescriptorFromJSONTyped(json, true);
        case DataTypeName.Pq:
            return PhysicalQuantityFromJSONTyped(json, true);
        case DataTypeName.TsDate:
        case DataTypeName.TsDatetime:
            return new Date(json);
        case DataTypeName.St:
            return json;
        default:
            return {} as any;
    }
}

export function ValueToJSON(json: any): any {
    return ValueToJSONTyped(json, false);
}

export function ValueToJSONTyped(value?: Value | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfConceptDescriptor(value)) {
        return ConceptDescriptorToJSON(value as ConceptDescriptor);
    }
    if (instanceOfPhysicalQuantity(value)) {
        return PhysicalQuantityToJSON(value as PhysicalQuantity);
    }
    if (typeof value === 'string') {
        return value;
    }
    if (value instanceof Date) {
        return value == null ? undefined : ((value).toISOString());
    }
    return {};
}

