/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ZeroedQuantity
 */
export interface ZeroedQuantity {
    /**
     * 
     * @type {string}
     * @memberof ZeroedQuantity
     */
    dataType: ZeroedQuantityDataTypeEnum;
}


/**
 * @export
 */
export const ZeroedQuantityDataTypeEnum = {
    Qtz: 'QTZ'
} as const;
export type ZeroedQuantityDataTypeEnum = typeof ZeroedQuantityDataTypeEnum[keyof typeof ZeroedQuantityDataTypeEnum];


/**
 * Check if a given object implements the ZeroedQuantity interface.
 */
export function instanceOfZeroedQuantity(value: object): value is ZeroedQuantity {
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    return true;
}

export function ZeroedQuantityFromJSON(json: any): ZeroedQuantity {
    return ZeroedQuantityFromJSONTyped(json, false);
}

export function ZeroedQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZeroedQuantity {
    if (json == null) {
        return json;
    }
    return {
        
        'dataType': json['data_type'],
    };
}

export function ZeroedQuantityToJSON(json: any): ZeroedQuantity {
    return ZeroedQuantityToJSONTyped(json, false);
}

export function ZeroedQuantityToJSONTyped(value?: ZeroedQuantity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data_type': value['dataType'],
    };
}

