name: BRIDG CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: Lint
        run: uv run ruff check


  lint-telegram-notification:
    needs: lint
    if: ${{ always() }}
    uses: ./.github/workflows/telegram-notification.yml
    with:
      status_text: ${{ needs.lint.result == 'success' && 'success' || 'failure' }}
      status_emoji: ${{ needs.lint.result == 'success' && '✅' || '❌' }}
      stage_name: "lint"
    secrets:
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
      bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  test:
    runs-on: ubuntu-latest
    env:
      BRIDG_ENV: testing
      PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7
      - name: Install python dependencies dependencies
        run: sudo apt install -y libjpeg-dev zlib1g-dev
      - name: Install python dependencies
        run: uv sync --all-packages --group test
      - name: Test alchemy
        run: uv run pytest packages/alchemy -s -vv
      - name: Test api
        run: uv run pytest packages/api -s -vv
      - name: Test graphql
        run: uv run pytest packages/graphql -s -vv
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: coverage
          path: htmlcov
          retention-days: 30

  test-telegram-notification:
    needs: test
    if: ${{ always() }}
    uses: ./.github/workflows/telegram-notification.yml
    with:
      status_text: ${{ needs.test.result == 'success' && 'success' || 'failure' }}
      status_emoji: ${{ needs.test.result == 'success' && '✅' || '❌' }}
      stage_name: "test"
    secrets:
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
      bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
