name: BRIDG CI

on:
  push:
    branches: [ main, api ]
  pull_request:
    branches: [ main, api ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui

    strategy:
      matrix:
        node-version: [ 22.17.x ]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Link API client
      run: npm link ../api-ts

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm test

