name: Telegram CI Notification

on:
  workflow_call:
    inputs:
      status_text:
        type: string
        required: true
        description: "Job status (success/failure)"
      status_emoji:
        type: string
        required: true
        description: "Job status emoji (success/failure)"
      stage_name:
        type: string
        required: true
        description: Job stage name
      working_directory:
        type: string
        default: ""
        description: "Project directory (e.g., ./ui)"
    secrets:
      chat_id:
        required: true
      bot_token:
        required: true

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          # Construct message
          MESSAGE=$(cat <<EOF
          ${{ inputs.status_emoji }} GitHub Actions CI Report for [${{ inputs.stage_name }}] ${{ inputs.status_emoji }}
          Commit: ${{ github.sha }}
          Author: ${{ github.actor }}
          PR url: ${{ github.event.pull_request.html_url }}
          CI LOG: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          )

          # URL encode the message
          ENCODED_MESSAGE=$(printf '%s' "$MESSAGE" | jq -sRr @uri)

          # Send message via Telegram Bot API
          TELEGRAM_API_URL="https://api.telegram.org/bot${{ secrets.bot_token }}/sendMessage"

          RESPONSE=$(curl -s -X POST "$TELEGRAM_API_URL" \
          -d "chat_id=${{ secrets.chat_id }}" \
          -d "disable_web_page_preview= true" \
          -d "text=${ENCODED_MESSAGE}")

          # Check if message was sent successfully
          if echo "$RESPONSE" | grep -q '"ok":true'; then
          echo "Telegram notification sent successfully"
          else
          echo "Failed to send Telegram notification"
          echo "$RESPONSE"
          exit 1
          fi
